import { Airline } from './types';

export const AIRLINE_DATA: Airline[] = [
  {
    id: 'delta-air-lines',
    continent: 'Amerika',
    name: 'Delta Air Lines',
    foundedYear: 1925,
    country: 'USA',
    hub: 'Atlanta (ATL)',
    alliance: 'SkyTeam',
    description: 'Delta Air Lines je jednou z nejstarších a největších leteckých společností na světě. Sídlí v Atlantě ve státě Georgie a provozuje rozsáhlou vnitrostátní i mezinárodní síť linek. Je zakládajícím členem aliance SkyTeam a její hlavní hub v Atlantě (Hartsfield-Jackson) je nejvytíženějším letištěm světa podle počtu cestujících.',
    logoUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-100', quantity: 45 },
      { aircraftId: 'airbus-a220-300', quantity: 26 },
      { aircraftId: 'airbus-a320-a319-100', quantity: 57 },
      { aircraftId: 'airbus-a320-200', quantity: 59 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 127 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 61 },
      { aircraftId: 'airbus-a330-200', quantity: 11 },
      { aircraftId: 'airbus-a330-300', quantity: 31 },
      { aircraftId: 'airbus-a330-900neo', quantity: 31 },
      { aircraftId: 'airbus-a350-900', quantity: 33 },
      { aircraftId: 'boeing-737-800', quantity: 77 },
      { aircraftId: 'boeing-737-900er', quantity: 163 },
      { aircraftId: 'boeing-757-200', quantity: 107 },
      { aircraftId: 'boeing-757-300', quantity: 16 },
      { aircraftId: 'boeing-767-300', quantity: 41 },
      { aircraftId: 'boeing-767-400er', quantity: 21 }
    ]
  },
  {
    id: 'lufthansa',
    continent: 'Evropa',
    name: 'Lufthansa',
    foundedYear: 1953,
    country: 'Německo',
    hub: 'Frankfurt (FRA) / Mnichov (MUC)',
    alliance: 'Star Alliance',
    description: 'Deutsche Lufthansa AG je německý národní letecký dopravce a jedna z největších leteckých skupin v Evropě. Je zakládajícím členem aliance Star Alliance. Lufthansa je známá svým špičkovým servisem, vysokými standardy bezpečnosti a provozem kultovních čtyřmotorových letadel Boeing 747 na dálkových trasách.',
    logoUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 29 },
      { aircraftId: 'airbus-a320-200', quantity: 53 },
      { aircraftId: 'airbus-a320-neo', quantity: 28 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 54 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 17 },
      { aircraftId: 'airbus-a330-300', quantity: 5 },
      { aircraftId: 'airbus-a340-300', quantity: 14 },
      { aircraftId: 'airbus-a340-600', quantity: 5 },
      { aircraftId: 'airbus-a350-900', quantity: 31 },
      { aircraftId: 'airbus-a380-800', quantity: 8 },
      { aircraftId: 'boeing-787-9', quantity: 5 },
      { aircraftId: 'boeing-747-400', quantity: 8 },
      { aircraftId: 'boeing-747-8', quantity: 19 }
    ]
  },
  {
    id: 'smartwings',
    continent: 'Evropa',
    name: 'Smartwings',
    foundedYear: 1997,
    country: 'Česká republika',
    hub: 'Praha (PRG)',
    alliance: '—',
    description: 'Smartwings, a.s. je česká letecká společnost se sídlem v Praze. Provozuje pravidelné linky, charterové lety a pronájmy letadel pro cestovní kanceláře a jiné letecké společnosti. Je největším leteckým dopravcem v České republice a provozuje moderní flotilu letadel řady Boeing 737.',
    logoUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-300', quantity: 4 },
      { aircraftId: 'airbus-a320-200', quantity: 2 },
      { aircraftId: 'boeing-737-800', quantity: 21 },
      { aircraftId: 'boeing-737-900er', quantity: 2 },
      { aircraftId: 'boeing-737-max-8', quantity: 14 }
    ]
  },
  {
    id: 'ryanair',
    continent: 'Evropa',
    name: 'Ryanair',
    foundedYear: 1984,
    country: 'Irsko',
    hub: 'Dublin (DUB)',
    alliance: '—',
    description: 'Ryanair je irská nízkonákladová letecká společnost se sídlem v Dublinu. Je největší nízkonákladovou leteckou společností v Evropě a jednou z největších na světě podle počtu přepravených cestujících. Provozuje obrovskou flotilu převážně letadel Boeing 737 a obsluhuje stovky destinací po celé Evropě, severní Africe a na Blízkém východě.',
    logoUrl: 'https://images.unsplash.com/photo-1520437358207-3dbf6f56bc15?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'boeing-737-700', quantity: 1 },
      { aircraftId: 'boeing-737-800', quantity: 410 },
      { aircraftId: 'boeing-737-max-8', quantity: 210 },
      { aircraftId: 'bombardier-challenger-3500', quantity: 3 },
      { aircraftId: 'bombardier-learjet-45', quantity: 1 }
    ]
  },
  {
    id: 'british-airways',
    continent: 'Evropa',
    name: 'British Airways',
    foundedYear: 1974,
    country: 'Velká Británie',
    hub: 'Londýn Heathrow (LHR)',
    alliance: 'oneworld',
    description: 'British Airways je vlajkový letecký dopravce Spojeného království se sídlem v Londýně. Je jedním z největších leteckých dopravců v Evropě a zakládajícím členem aliance oneworld. Provozuje rozsáhlou globální síť linek z hlavního uzlu na letišti Londýn Heathrow.',
    logoUrl: 'https://images.unsplash.com/photo-1483450388369-9ed95738483c?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 29 },
      { aircraftId: 'airbus-a320-200', quantity: 67 },
      { aircraftId: 'airbus-a320-neo', quantity: 25 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 15 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 13 },
      { aircraftId: 'airbus-a350-1000', quantity: 18 },
      { aircraftId: 'airbus-a380-800', quantity: 12 },
      { aircraftId: 'boeing-777-200er', quantity: 43 },
      { aircraftId: 'boeing-777-300er', quantity: 16 },
      { aircraftId: 'boeing-787-8', quantity: 12 },
      { aircraftId: 'boeing-787-9', quantity: 18 },
      { aircraftId: 'boeing-787-10', quantity: 10 }
    ]
  },
  {
    id: 'klm',
    continent: 'Evropa',
    name: 'KLM',
    foundedYear: 1919,
    country: 'Nizozemsko',
    hub: 'Amsterdam (AMS)',
    alliance: 'SkyTeam',
    description: 'KLM Royal Dutch Airlines (Koninklijke Luchtvaart Maatschappij) je národní letecký dopravce Nizozemska se sídlem v Amstelveenu, s hlavním uzlem na letišti Schiphol v Amsterdamu. Založena v roce 1919, KLM je nejstarší leteckou společností na světě, která stále operuje pod svým původním názvem.',
    logoUrl: 'https://images.unsplash.com/photo-1473862170180-84427c485ade?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a321-neo', quantity: 6 },
      { aircraftId: 'airbus-a330-200', quantity: 6 },
      { aircraftId: 'airbus-a330-300', quantity: 5 },
      { aircraftId: 'boeing-737-700', quantity: 6 },
      { aircraftId: 'boeing-737-800', quantity: 31 },
      { aircraftId: 'boeing-737-900', quantity: 5 },
      { aircraftId: 'boeing-777-200er', quantity: 15 },
      { aircraftId: 'boeing-777-300er', quantity: 16 },
      { aircraftId: 'boeing-787-9', quantity: 13 },
      { aircraftId: 'boeing-787-10', quantity: 10 }
    ]
  },
  {
    id: 'qatar-airways',
    continent: 'Asie',
    name: 'Qatar Airways',
    foundedYear: 1993,
    country: 'Katar',
    hub: 'Dauhá (DOH)',
    alliance: 'oneworld',
    description: 'Qatar Airways je státní národní letecký dopravce Kataru se sídlem v Dauhá. Společnost propojuje přes 150 mezinárodních destinací po celém světě ze svého hlavního uzlu na letišti Hamad. Je známá svým luxusním servisem Qsuite a opakovaně získala ocenění pro nejlepší leteckou společnost světa v hodnocení Skytrax.',
    logoUrl: 'https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-200', quantity: 29 },
      { aircraftId: 'airbus-a330-200f', quantity: 2 },
      { aircraftId: 'airbus-a350-900', quantity: 34 },
      { aircraftId: 'airbus-a350-1000', quantity: 24 },
      { aircraftId: 'airbus-a380-800', quantity: 10 },
      { aircraftId: 'boeing-737-max-8', quantity: 9 },
      { aircraftId: 'boeing-737-max-10', quantity: 1 },
      { aircraftId: 'boeing-777-200lr', quantity: 7 },
      { aircraftId: 'boeing-777-300er', quantity: 57 },
      { aircraftId: 'boeing-777f', quantity: 28 },
      { aircraftId: 'boeing-787-8', quantity: 30 },
      { aircraftId: 'boeing-787-9', quantity: 18 }
    ]
  },
  {
    id: 'wizz-air',
    continent: 'Evropa',
    name: 'Wizz Air',
    foundedYear: 2003,
    country: 'Maďarsko',
    hub: 'Budapešť (BUD)',
    alliance: '—',
    description: 'Wizz Air je maďarská nízkonákladová letecká společnost se sídlem v Budapešti. Je jednou z největších nízkonákladových leteckých společností ve střední a východní Evropě a provozuje rozsáhlou síť linek propojující desítky zemí v Evropě, na Blízkém východě a v severní Africe s moderní flotilou letadel Airbus.',
    logoUrl: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-200', quantity: 39 },
      { aircraftId: 'airbus-a320-neo', quantity: 6 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 41 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 122 },
      { aircraftId: 'airbus-a330-200f', quantity: 1 }
    ]
  },
  {
    id: 'singapore-airlines',
    continent: 'Asie',
    name: 'Singapore Airlines',
    foundedYear: 1947,
    country: 'Singapur',
    hub: 'Singapur Changi (SIN)',
    alliance: 'Star Alliance',
    description: 'Singapore Airlines jsou vlajkovým leteckým dopravcem Singapuru s hlavním uzlem na letišti Changi. Jsou známé svými mimořádně vysokými standardy služeb, luxusními kabinami a tím, že jako první na světě uvedly do provozu obří letoun Airbus A380.',
    logoUrl: 'https://images.unsplash.com/photo-1570737197260-ac5797771228?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a350-900', quantity: 62 },
      { aircraftId: 'airbus-a380-800', quantity: 12 },
      { aircraftId: 'boeing-737-max-8', quantity: 16 },
      { aircraftId: 'boeing-777-300er', quantity: 22 },
      { aircraftId: 'boeing-777f', quantity: 5 },
      { aircraftId: 'boeing-747-400f', quantity: 7 },
      { aircraftId: 'boeing-787-10', quantity: 25 }
    ]
  },
  {
    id: 'tap-portugal',
    continent: 'Evropa',
    name: 'TAP Air Portugal',
    foundedYear: 1945,
    country: 'Portugalsko',
    hub: 'Lisabon (LIS)',
    alliance: 'Star Alliance',
    description: 'TAP Air Portugal je národní letecký dopravce Portugalska se sídlem v Lisabonu. Je členem Star Alliance a provozuje rozsáhlou síť linek, zejména do Severní a Jižní Ameriky a Afriky, s moderní celoairbusovou flotilou.',
    logoUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 3 },
      { aircraftId: 'airbus-a320-200', quantity: 15 },
      { aircraftId: 'airbus-a320-neo', quantity: 16 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 3 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 24 },
      { aircraftId: 'airbus-a330-200', quantity: 3 },
      { aircraftId: 'airbus-a330-900neo', quantity: 19 }
    ]
  },
  {
    id: 'air-canada',
    continent: 'Amerika',
    name: 'Air Canada',
    foundedYear: 1937,
    country: 'Kanada',
    hub: 'Toronto Pearson (YYZ)',
    alliance: 'Star Alliance',
    description: 'Air Canada je největší letecká společnost a národní dopravce Kanady se sídlem v Montrealu. Je zakládajícím členem Star Alliance a propojuje desítky destinací na šesti kontinentech z hlavních uzlů v Torontu, Vancouveru a Montrealu.',
    logoUrl: 'https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-300', quantity: 42 },
      { aircraftId: 'airbus-a320-200', quantity: 14 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 16 },
      { aircraftId: 'airbus-a321-xlr', quantity: 6 },
      { aircraftId: 'airbus-a330-300', quantity: 20 },
      { aircraftId: 'boeing-737-max-8', quantity: 45 },
      { aircraftId: 'boeing-777-200lr', quantity: 6 },
      { aircraftId: 'boeing-777-300er', quantity: 19 },
      { aircraftId: 'boeing-787-8', quantity: 8 },
      { aircraftId: 'boeing-787-9', quantity: 32 }
    ]
  },
  {
    id: 'finnair',
    continent: 'Evropa',
    name: 'Finnair',
    foundedYear: 1923,
    country: 'Finsko',
    hub: 'Helsinky (HEL)',
    alliance: 'oneworld',
    description: 'Finnair je finský národní letecký dopravce se sídlem v Vantaa, Helsinkách. Je jedním z nejstarších nepřetržitě fungujících leteckých dopravců na světě a členem aliance oneworld. Specializuje se na rychlé spojení mezi Evropou a Asií přes severní polární trasu.',
    logoUrl: 'https://images.unsplash.com/photo-1517479149777-5f3b1511d5ad?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 5 },
      { aircraftId: 'airbus-a320-200', quantity: 10 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 15 },
      { aircraftId: 'airbus-a330-300', quantity: 8 },
      { aircraftId: 'airbus-a350-900', quantity: 17 }
    ]
  },
  {
    id: 'united-airlines',
    continent: 'Amerika',
    name: 'United Airlines',
    foundedYear: 1926,
    country: 'USA',
    hub: 'Chicago O\'Hare (ORD)',
    alliance: 'Star Alliance',
    description: 'United Airlines je jednou z největších leteckých společností na světě se sídlem v Chicagu, Illinois. Provozuje rozsáhlou vnitrostátní i mezinárodní síť s klíčovými uzly jako Chicago O\'Hare, Denver, Houston a Newark. Je zakládajícím členem Star Alliance.',
    logoUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 72 },
      { aircraftId: 'airbus-a320-200', quantity: 66 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 68 },
      { aircraftId: 'airbus-a321-xlr', quantity: 1 },
      { aircraftId: 'boeing-737-700', quantity: 40 },
      { aircraftId: 'boeing-737-800', quantity: 141 },
      { aircraftId: 'boeing-737-900', quantity: 12 },
      { aircraftId: 'boeing-737-900er', quantity: 136 },
      { aircraftId: 'boeing-737-max-8', quantity: 123 },
      { aircraftId: 'boeing-737-max-9', quantity: 153 },
      { aircraftId: 'boeing-757-200', quantity: 40 },
      { aircraftId: 'boeing-757-300', quantity: 21 },
      { aircraftId: 'boeing-767-300', quantity: 37 },
      { aircraftId: 'boeing-767-400er', quantity: 16 },
      { aircraftId: 'boeing-777-200', quantity: 19 },
      { aircraftId: 'boeing-777-200er', quantity: 55 },
      { aircraftId: 'boeing-777-300er', quantity: 22 },
      { aircraftId: 'boeing-787-8', quantity: 12 },
      { aircraftId: 'boeing-787-9', quantity: 54 },
      { aircraftId: 'boeing-787-10', quantity: 21 }
    ]
  },
  {
    id: 'american-airlines',
    continent: 'Amerika',
    name: 'American Airlines',
    foundedYear: 1930,
    country: 'USA',
    hub: 'Dallas/Fort Worth (DFW)',
    alliance: 'oneworld',
    description: 'American Airlines je největší letecká společnost na světě podle velikosti flotily a počtu přepravených cestujících, se sídlem ve Fort Worthu v Texasu. Je zakládajícím členem aliance oneworld a jejím největším uzlem je letiště Dallas/Fort Worth.',
    logoUrl: 'https://images.unsplash.com/photo-1544016768-982d1554f0b9?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 132 },
      { aircraftId: 'airbus-a320-200', quantity: 48 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 218 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 84 },
      { aircraftId: 'airbus-a321-xlr', quantity: 5 },
      { aircraftId: 'boeing-737-800', quantity: 303 },
      { aircraftId: 'boeing-737-max-8', quantity: 103 },
      { aircraftId: 'boeing-777-200er', quantity: 47 },
      { aircraftId: 'boeing-777-300er', quantity: 20 },
      { aircraftId: 'boeing-787-8', quantity: 37 },
      { aircraftId: 'boeing-787-9', quantity: 33 }
    ]
  },
  {
    id: 'turkish-airlines',
    continent: 'Evropa',
    name: 'Turkish Airlines',
    foundedYear: 1933,
    country: 'Turecko',
    hub: 'Istanbul (IST)',
    alliance: 'Star Alliance',
    description: 'Turkish Airlines je národní letecký dopravce Turecka se sídlem v Istanbulu. Létá do více destinací bez mezipřistání než kterákoli jiná letecká společnost na světě. Jejím hlavním uzlem je moderní letiště Istanbul Airport a je členem Star Alliance.',
    logoUrl: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-200', quantity: 6 },
      { aircraftId: 'airbus-a320-neo', quantity: 9 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 65 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 60 },
      { aircraftId: 'airbus-a330-200', quantity: 13 },
      { aircraftId: 'airbus-a330-300', quantity: 36 },
      { aircraftId: 'airbus-a350-900', quantity: 22 },
      { aircraftId: 'airbus-a350-1000', quantity: 2 },
      { aircraftId: 'boeing-737-800', quantity: 40 },
      { aircraftId: 'boeing-737-900er', quantity: 15 },
      { aircraftId: 'boeing-737-max-8', quantity: 20 },
      { aircraftId: 'boeing-737-max-9', quantity: 5 },
      { aircraftId: 'boeing-777-300er', quantity: 34 },
      { aircraftId: 'boeing-777f', quantity: 8 },
      { aircraftId: 'boeing-787-9', quantity: 23 }
    ]
  },
  {
    id: 'ana',
    continent: 'Asie',
    name: 'All Nippon Airways',
    foundedYear: 1952,
    country: 'Japonsko',
    hub: 'Tokio Haneda (HND) / Narita (NRT)',
    alliance: 'Star Alliance',
    description: 'All Nippon Airways (ANA) je největší letecká společnost v Japonsku se sídlem v Tokiu. Provozuje rozsáhlou síť vnitrostátních a mezinárodních linek z hlavních uzlů na letištích Haneda a Narita a je členem Star Alliance. Je známá svými výjimečnými službami a pětihvězdičkovým hodnocením.',
    logoUrl: 'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-200', quantity: 13 },
      { aircraftId: 'airbus-a320-neo', quantity: 33 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 4 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 25 },
      { aircraftId: 'airbus-a380-800', quantity: 3 },
      { aircraftId: 'boeing-737-800', quantity: 39 },
      { aircraftId: 'boeing-767-300', quantity: 15 },
      { aircraftId: 'boeing-767-300f', quantity: 6 },
      { aircraftId: 'boeing-777-200', quantity: 10 },
      { aircraftId: 'boeing-777-300', quantity: 16 },
      { aircraftId: 'boeing-777f', quantity: 2 },
      { aircraftId: 'boeing-747-8f', quantity: 8 },
      { aircraftId: 'boeing-787-8', quantity: 36 },
      { aircraftId: 'boeing-787-9', quantity: 44 },
      { aircraftId: 'boeing-787-10', quantity: 10 },
      { aircraftId: 'bombardier-dhc-8-400', quantity: 25 }
    ]
  },
  {
    id: 'emirates',
    continent: 'Asie',
    name: 'Emirates',
    foundedYear: 1985,
    country: 'Spojené arabské emiráty',
    hub: 'Dubaj (DXB)',
    alliance: '—',
    description: 'Emirates je jedna z největších leteckých společností na světě se sídlem v Dubaji v SAE. Je známá svým luxusním servisem, flotilou složenou výhradně ze širokotrupých letadel Airbus A380 a Boeing 777 a svým globálním uzlem na letišti v Dubaji.',
    logoUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a380-800', quantity: 116 },
      { aircraftId: 'boeing-777-200lr', quantity: 10 },
      { aircraftId: 'boeing-777-300er', quantity: 122 },
      { aircraftId: 'boeing-777f', quantity: 11 }
    ]
  },
  {
    id: 'qantas',
    continent: 'Austrálie a Oceánie',
    name: 'Qantas',
    foundedYear: 1920,
    country: 'Austrálie',
    hub: 'Sydney (SYD)',
    alliance: 'oneworld',
    description: 'Qantas je australský národní letecký dopravce a jedna z nejstarších nepřetržitě fungujících leteckých společností na světě. Je zakládajícím členem aliance oneworld a provozuje rozsáhlou vnitrostátní i mezinárodní síť s klíčovými uzly v Sydney, Melbourne a Brisbane.',
    logoUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-300', quantity: 6 },
      { aircraftId: 'airbus-a320-200', quantity: 15 },
      { aircraftId: 'airbus-a330-200', quantity: 16 },
      { aircraftId: 'airbus-a330-300', quantity: 10 },
      { aircraftId: 'airbus-a380-800', quantity: 10 },
      { aircraftId: 'boeing-737-800', quantity: 75 },
      { aircraftId: 'boeing-787-9', quantity: 14 }
    ]
  },
  {
    id: 'korean-air',
    continent: 'Asie',
    name: 'Korean Air',
    foundedYear: 1969,
    country: 'Jižní Korea',
    hub: 'Soul Inčchon (ICN)',
    alliance: 'SkyTeam',
    description: 'Korean Air je největší letecká společnost a národní dopravce Jižní Koreje se sídlem v Soulu. Je zakládajícím členem aliance SkyTeam a provozuje rozsáhlou globální síť spojující Asii, Ameriku, Evropu a Austrálii z hlavního uzlu na letišti Inčchon.',
    logoUrl: 'https://images.unsplash.com/photo-1542296332-2e4473fac563?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-300', quantity: 10 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 12 },
      { aircraftId: 'airbus-a330-200', quantity: 4 },
      { aircraftId: 'airbus-a330-300', quantity: 19 },
      { aircraftId: 'airbus-a380-800', quantity: 8 },
      { aircraftId: 'boeing-737-800', quantity: 2 },
      { aircraftId: 'boeing-737-900', quantity: 2 },
      { aircraftId: 'boeing-737-900er', quantity: 6 },
      { aircraftId: 'boeing-737-max-8', quantity: 6 },
      { aircraftId: 'boeing-747-8', quantity: 9 },
      { aircraftId: 'boeing-747-400f', quantity: 4 },
      { aircraftId: 'boeing-747-8f', quantity: 7 },
      { aircraftId: 'boeing-777-200er', quantity: 4 },
      { aircraftId: 'boeing-777-300', quantity: 4 },
      { aircraftId: 'boeing-777-300er', quantity: 25 },
      { aircraftId: 'boeing-777f', quantity: 12 },
      { aircraftId: 'boeing-787-9', quantity: 14 },
      { aircraftId: 'boeing-787-10', quantity: 3 }
    ]
  },
  {
    id: 'vueling',
    continent: 'Evropa',
    name: 'Vueling',
    foundedYear: 2004,
    country: 'Španělsko',
    hub: 'Barcelona (BCN)',
    alliance: '—',
    description: 'Vueling je španělská nízkonákladová letecká společnost se sídlem ve Viladecans u Barcelony. Je druhou největší leteckou společností ve Španělsku a provozuje rozsáhlou evropskou síť s hlavními uzly v Barceloně a Římě.',
    logoUrl: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 6 },
      { aircraftId: 'airbus-a320-200', quantity: 64 },
      { aircraftId: 'airbus-a320-neo', quantity: 25 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 18 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 4 }
    ]
  },
  {
    id: 'cathay-pacific',
    continent: 'Asie',
    name: 'Cathay Pacific',
    foundedYear: 1946,
    country: 'Hongkong',
    hub: 'Hongkong (HKG)',
    alliance: 'oneworld',
    description: 'Cathay Pacific je vlajkový letecký dopravce Hongkongu se sídlem na letišti v Hongkongu. Je zakládajícím členem aliance oneworld a je známý svými vysokými standardy kvality služeb a rozsáhlou globální sítí přepravy cestujících i nákladu.',
    logoUrl: 'https://images.unsplash.com/photo-1500835595337-f740027392b9?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a321-neo', quantity: 15 },
      { aircraftId: 'airbus-a330-300', quantity: 43 },
      { aircraftId: 'airbus-a350-900', quantity: 30 },
      { aircraftId: 'airbus-a350-1000', quantity: 18 },
      { aircraftId: 'boeing-747-400f', quantity: 6 },
      { aircraftId: 'boeing-747-8f', quantity: 14 },
      { aircraftId: 'boeing-777-300', quantity: 17 },
      { aircraftId: 'boeing-777-300er', quantity: 37 }
    ]
  },
  {
    id: 'air-france',
    continent: 'Evropa',
    name: 'Air France',
    foundedYear: 1933,
    country: 'Francie',
    hub: 'Paříž Charles de Gaulle (CDG)',
    alliance: 'SkyTeam',
    description: 'Air France je vlajkový francouzský letecký dopravce se sídlem v Paříži. Patří mezi nejstarší a nejvýznamnější aerolinky na světě. Je zakládajícím členem aliance SkyTeam a její hlavní základna se nachází na letišti Charlese de Gaulla v Paříži.',
    logoUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-300', quantity: 37 },
      { aircraftId: 'airbus-a320-a319-100', quantity: 11 },
      { aircraftId: 'airbus-a320-200', quantity: 36 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 15 },
      { aircraftId: 'airbus-a330-200', quantity: 15 },
      { aircraftId: 'airbus-a350-900', quantity: 32 },
      { aircraftId: 'boeing-777-200er', quantity: 18 },
      { aircraftId: 'boeing-777-300er', quantity: 43 },
      { aircraftId: 'boeing-787-9', quantity: 10 }
    ]
  },
  {
    id: 'iberia',
    continent: 'Evropa',
    name: 'Iberia',
    foundedYear: 1927,
    country: 'Španělsko',
    hub: 'Madrid (MAD)',
    alliance: 'oneworld',
    description: 'Iberia je národní letecká společnost Španělska se sídlem v Madridu. Je členem aliance oneworld a provozuje rozsáhlou síť mezinárodních spojů, přičemž je klíčovým mostem mezi Evropou a Latinskou Amerikou.',
    logoUrl: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 6 },
      { aircraftId: 'airbus-a320-200', quantity: 13 },
      { aircraftId: 'airbus-a320-neo', quantity: 17 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 11 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 6 },
      { aircraftId: 'airbus-a330-200', quantity: 16 },
      { aircraftId: 'airbus-a330-300', quantity: 8 },
      { aircraftId: 'airbus-a350-900', quantity: 22 }
    ]
  },
  {
    id: 'sas',
    continent: 'Evropa',
    name: 'SAS - Scandinavian Airlines',
    foundedYear: 1946,
    country: 'Švédsko / Norsko / Dánsko',
    hub: 'Kodaň (CPH) / Oslo (OSL) / Stockholm (ARN)',
    alliance: 'SkyTeam',
    description: 'Scandinavian Airlines (SAS) je vlajkový letecký dopravce pro Skandinávii (Dánsko, Norsko a Švédsko). Společnost provozuje lety ze svých hlavních základen v Kodani, Oslu a Stockholmu.',
    logoUrl: 'https://images.unsplash.com/photo-1520437358207-3dbf6f56bc15?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 4 },
      { aircraftId: 'airbus-a320-200', quantity: 11 },
      { aircraftId: 'airbus-a320-neo', quantity: 36 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 3 },
      { aircraftId: 'airbus-a330-300', quantity: 7 },
      { aircraftId: 'airbus-a350-900', quantity: 4 },
      { aircraftId: 'boeing-737-700', quantity: 4 },
      { aircraftId: 'embraer-e195', quantity: 10 }
    ]
  },
  {
    id: 'brussels-airlines',
    continent: 'Evropa',
    name: 'Brussels Airlines',
    foundedYear: 2002,
    country: 'Belgie',
    hub: 'Brusel (BRU)',
    alliance: 'Star Alliance',
    description: 'Brussels Airlines je národní belgický letecký dopravce se sídlem v Bruselu. Je členem skupiny Lufthansa Group a aliance Star Alliance. Provozuje lety do Evropy, Severní Ameriky a Afriky.',
    logoUrl: 'https://images.unsplash.com/photo-1483450388369-9ed95738483c?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-a319-100', quantity: 15 },
      { aircraftId: 'airbus-a320-200', quantity: 16 },
      { aircraftId: 'airbus-a320-neo', quantity: 5 },
      { aircraftId: 'airbus-a330-300', quantity: 10 }
    ]
  },
  {
    id: 'lot-polish-airlines',
    continent: 'Evropa',
    name: 'LOT Polish Airlines',
    foundedYear: 1928,
    country: 'Polsko',
    hub: 'Varšava (WAW)',
    alliance: 'Star Alliance',
    description: 'LOT Polish Airlines je polský národní letecký dopravce se sídlem ve Varšavě. Patří mezi nejstarší aerolinky na světě. Je členem aliance Star Alliance a provozuje rozsáhlou síť letů po Evropě, Severní Americe a Asii ze svého hlavního uzlu na letišti Chopina ve Varšavě.',
    logoUrl: 'https://images.unsplash.com/photo-1473862170180-84427c485ade?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'boeing-737-800', quantity: 6 },
      { aircraftId: 'boeing-737-max-8', quantity: 11 },
      { aircraftId: 'boeing-787-8', quantity: 8 },
      { aircraftId: 'boeing-787-9', quantity: 7 },
      { aircraftId: 'embraer-e170', quantity: 6 },
      { aircraftId: 'embraer-e175', quantity: 15 },
      { aircraftId: 'embraer-e190', quantity: 8 },
      { aircraftId: 'embraer-e195', quantity: 15 }
    ]
  },
  {
    id: 'austrian-airlines',
    continent: 'Evropa',
    name: 'Austrian Airlines',
    foundedYear: 1957,
    country: 'Rakousko',
    hub: 'Vídeň (VIE)',
    alliance: 'Star Alliance',
    description: 'Austrian Airlines je národní letecká společnost Rakouska se sídlem ve Vídni. Je dceřinou společností Lufthansa Group a členem aliance Star Alliance. Provozuje rozsáhlou síť letů s důrazem na střední a východní Evropu a Blízký východ.',
    logoUrl: 'https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-200', quantity: 29 },
      { aircraftId: 'airbus-a320-neo', quantity: 5 },
      { aircraftId: 'airbus-a320-a321-100', quantity: 3 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 3 },
      { aircraftId: 'boeing-777-200er', quantity: 6 },
      { aircraftId: 'boeing-787-9', quantity: 2 },
      { aircraftId: 'embraer-e195', quantity: 17 }
    ]
  },
  {
    id: 'swiss-international',
    continent: 'Evropa',
    name: 'Swiss International Air Lines',
    foundedYear: 2002,
    country: 'Švýcarsko',
    hub: 'Curych (ZRH) / Ženeva (GVA)',
    alliance: 'Star Alliance',
    description: 'Swiss International Air Lines (SWISS) je hlavní letecký dopravce Švýcarska. Vznikl po úpadku společnosti Swissair a je součástí skupiny Lufthansa Group. Je členem aliance Star Alliance a vyniká špičkovou kvalitou služeb a typickou švýcarskou pohostinností.',
    logoUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a220-100', quantity: 9 },
      { aircraftId: 'airbus-a220-300', quantity: 21 },
      { aircraftId: 'airbus-a320-200', quantity: 11 },
      { aircraftId: 'airbus-a320-neo', quantity: 7 },
      { aircraftId: 'airbus-a320-a321-100', quantity: 3 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 3 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 4 },
      { aircraftId: 'airbus-a330-300', quantity: 14 },
      { aircraftId: 'airbus-a340-300', quantity: 4 },
      { aircraftId: 'boeing-777-300er', quantity: 12 }
    ]
  },
  {
    id: 'etihad-airways',
    continent: 'Asie',
    name: 'Etihad Airways',
    foundedYear: 2003,
    country: 'SAE',
    hub: 'Abú Zabí (AUH)',
    alliance: '—',
    description: 'Etihad Airways je jednou ze dvou národních leteckých společností Spojených arabských emirátů (druhou je Emirates). Sídlí v Abú Zabí a provozuje rozsáhlou mezinárodní síť spojující Evropu, Asii, Afriku, Ameriku a Austrálii. Je známá svým mimořádným luxusem v první a byznys třídě.',
    logoUrl: 'https://images.unsplash.com/photo-1542296332-2e4473fac563?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a320-200', quantity: 14 },
      { aircraftId: 'airbus-a320-a321-200', quantity: 9 },
      { aircraftId: 'airbus-a320-a321-neo', quantity: 5 },
      { aircraftId: 'airbus-a350-1000', quantity: 5 },
      { aircraftId: 'airbus-a380-800', quantity: 4 },
      { aircraftId: 'boeing-777-300er', quantity: 7 },
      { aircraftId: 'boeing-787-9', quantity: 33 },
      { aircraftId: 'boeing-787-10', quantity: 10 }
    ]
  },
  {
    id: 'japan-airlines',
    continent: 'Asie',
    name: 'Japan Airlines (JAL)',
    foundedYear: 1951,
    country: 'Japonsko',
    hub: 'Tokio Haneda (HND) / Tokio Narita (NRT)',
    alliance: 'oneworld',
    description: 'Japan Airlines (JAL) je národní letecká společnost Japonska se sídlem v Tokiu. Je členem aliance oneworld a patří mezi nejvytíženější a nejlépe hodnocené letecké společnosti v Asii. Vyniká vysokým standardem služeb, bezpečností a přesností letů.',
    logoUrl: 'https://images.unsplash.com/photo-1500835595337-f740027392b9?auto=format&fit=crop&w=600&q=80',
    fleet: [
      { aircraftId: 'airbus-a350-900', quantity: 15 },
      { aircraftId: 'airbus-a350-1000', quantity: 5 },
      { aircraftId: 'boeing-737-800', quantity: 62 },
      { aircraftId: 'boeing-767-300', quantity: 25 },
      { aircraftId: 'boeing-777-300er', quantity: 13 },
      { aircraftId: 'boeing-787-8', quantity: 23 },
      { aircraftId: 'boeing-787-9', quantity: 22 }
    ]
  }
];
