import { Aircraft } from './types';

export const AIRCRAFT_DATA: Aircraft[] = [
  // AIRBUS MODELS
  {
    id: 'airbus-a220-100',
    name: 'Airbus A220-100',
    modelSeries: 'A220 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie / Kanada',
    category: 'Regionální (Regional)',
    description: 'Menší varianta z rodiny A220 (původně Bombardier CS100). Je speciálně navržena pro kratší až středně dlouhé tratě a vyniká schopností operovat z letišť s extrémně krátkou vzletovou dráhou a strmým přiblížením, jako je například letiště London City. Nabízí bezkonkurenční hospodárnost v kategorii letadel pro 100 až 135 cestujících.',
    uniqueness: 'Je certifikován pro strmé přiblížení (steep approach) pod úhlem 5,5 stupně, což mu umožňuje přistávat bezpečně přímo v centrech měst na obtížně dostupných ranvejích.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Airbus_A220-300_C-FFDO_Paris_Air_Show_2019_y_2.jpg',
    authorName: 'Anna Zvereva / Wikimedia Commons',
    specs: {
      capacityMax: 135,
      capacityTypical: '100 - 120 (2 třídy)',
      rangeKm: 6390,
      cruiseSpeedKmh: 829,
      cruiseMach: 0.78,
      wingspanM: 35.1,
      lengthM: 35.0,
      heightM: 11.5,
      fuselageWidthM: 3.5,
      wingAreaM2: 112.3,
      mtowTonnes: 63.1,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW1500G',
      firstFlightYear: 2013,
    }
  },
  {
    id: 'airbus-a220-300',
    name: 'Airbus A220-300',
    modelSeries: 'A220 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie / Kanada',
    category: 'Regionální (Regional)',
    description: 'Prodloužená a nejpopulárnější verze řady A220 (původně Bombardier CS300). S delším trupem pojme až 160 cestujících, přičemž si zachovává mimořádně nízké provozní náklady a špičkovou palivovou účinnost. Díky moderní aerodynamice a kompozitním materiálům představuje ideální volbu pro flexibilní regionální i mezikontinentální linky.',
    uniqueness: 'Vyznačuje se extrémně nízkou hlukovou stopou – hluk na zemi v okolí letišť je až o 50 % nižší než u starších letadel srovnatelné velikosti.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Airbus_A220-300_C-FFDO_Paris_Air_Show_2019_y_2.jpg',
    authorName: 'Anna Zvereva / Wikimedia Commons',
    specs: {
      capacityMax: 160,
      capacityTypical: '120 - 150 (2 třídy)',
      rangeKm: 6297,
      cruiseSpeedKmh: 829,
      cruiseMach: 0.78,
      wingspanM: 35.1,
      lengthM: 38.7,
      heightM: 11.5,
      fuselageWidthM: 3.5,
      wingAreaM2: 112.3,
      mtowTonnes: 70.9,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW1500G',
      firstFlightYear: 2015,
    }
  },
  {
    id: 'airbus-a300-b2',
    name: 'Airbus A300B2',
    modelSeries: 'A300 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Původní základní produkční verze prvního širokotrupého dvoumotorového letadla na světě. Vstoupilo do komerční služby v roce 1974 u Air France. Tento průkopnický stroj prokázal, že i velká letadla pro dálkové linky mohou létat ekonomicky a bezpečně pouze se dvěma motory, čímž položil základy úspěchu celého konsorcia Airbus.',
    uniqueness: 'Vůbec první širokotrupé letadlo na světě poháněné pouze dvěma proudovými motory, které navždy změnilo strukturu dálkové civilní dopravy.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Airbus_A300B4-605R%2C_United_Airlines_JP6347898.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 345,
      capacityTypical: '250 - 270 (2 třídy)',
      rangeKm: 3430,
      cruiseSpeedKmh: 847,
      cruiseMach: 0.78,
      wingspanM: 44.84,
      lengthM: 53.62,
      heightM: 16.53,
      fuselageWidthM: 5.64,
      wingAreaM2: 260.0,
      mtowTonnes: 142.0,
      engineCount: 2,
      engineType: 'General Electric CF6-50A / Pratt & Whitney JT9D-59A',
      firstFlightYear: 1972,
    }
  },
  {
    id: 'airbus-a300-b4200ff',
    name: 'Airbus A300B4-200FF',
    modelSeries: 'A300 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Verze se zvýšeným doletem a unikátním uspořádáním kokpitu "Forward Facing Crew Cockpit" (FFCC). Tento model byl klíčovým technologickým přechodem v letectví – šlo o první širokotrupé letadlo, u kterého byl kokpit upraven tak, aby jej plně obsluhovali pouze dva piloti bez nutnosti přítomnosti palubního inženýra.',
    uniqueness: 'První širokotrupý letoun s inovovaným digitálním kokpitem orientovaným dopředu, který odstranil potřebu třetího člena posádky (palubního inženýra).',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Airbus_A300B4-605R%2C_United_Airlines_JP6347898.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 345,
      capacityTypical: '250 - 270 (2 třídy)',
      rangeKm: 5300,
      cruiseSpeedKmh: 847,
      cruiseMach: 0.78,
      wingspanM: 44.84,
      lengthM: 53.62,
      heightM: 16.53,
      fuselageWidthM: 5.64,
      wingAreaM2: 260.0,
      mtowTonnes: 165.0,
      engineCount: 2,
      engineType: 'General Electric CF6-50C2 / Pratt & Whitney JT9D-59',
      firstFlightYear: 1981,
    }
  },
  {
    id: 'airbus-a300-600r',
    name: 'Airbus A300-600R',
    modelSeries: 'A300 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nejmodernější a komerčně nejúspěšnější osobní verze řady A300. Model disponuje integrovaným glass-kokpitem z typu A310, vylepšenou aerodynamikou, modernějšími motory a přídavnou nádrží v ocasní sekci pro maximalizaci doletu. Stal se standardem pro dálkové linky na přelomu 80. a 90. let.',
    uniqueness: 'Představil přídavnou ocasní palivovou nádrž ovládanou automatickým trimovacím systémem pro optimální polohu těžiště během dálkového letu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Airbus_A300B4-605R%2C_United_Airlines_JP6347898.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 360,
      capacityTypical: '266 (2 třídy)',
      rangeKm: 7540,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.78,
      wingspanM: 44.84,
      lengthM: 54.08,
      heightM: 16.62,
      fuselageWidthM: 5.64,
      wingAreaM2: 260.0,
      mtowTonnes: 171.7,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2 / Pratt & Whitney PW4000',
      firstFlightYear: 1983,
    }
  },
  {
    id: 'airbus-a300-600f',
    name: 'Airbus A300-600F',
    modelSeries: 'A300 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Vysoce efektivní čistě nákladní širokotrupá verze, která sdílí modernizovaný drak a avioniku s osobním modelem -600R. Díky obří kapacitě nákladového prostoru a vynikající spolehlivosti tvoří dodnes páteř flotil předních světových expresních přepravců jako FedEx, DHL a UPS.',
    uniqueness: 'Jedno z nejúspěšnějších středněkapacitních nákladních letadel historie, schopné pojmout až 48,3 tun nákladu na dálkových i regionálních trasách.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Airbus_A300B4-605R%2C_United_Airlines_JP6347898.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (až 48,3 tun)',
      rangeKm: 4850,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.78,
      wingspanM: 44.84,
      lengthM: 54.08,
      heightM: 16.62,
      fuselageWidthM: 5.64,
      wingAreaM2: 260.0,
      mtowTonnes: 170.1,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2 / Pratt & Whitney PW4000',
      firstFlightYear: 1993,
    }
  },
  {
    id: 'airbus-a310-100',
    name: 'Airbus A310-100',
    modelSeries: 'A310 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Méně známá a nerealizovaná plánovaná regionální / krátkotrupá verze s kratším doletem určená pro evropské linky s vysokou poptávkou. Přestože byla vyvinuta a nabízena dopravcům v počátcích projektu, žádná verze -100 nakonec nebyla kvůli nízkému zájmu leteckých společností vyrobena a všichni zákazníci přešli na univerzálnější verzi -200.',
    uniqueness: 'Jedná se o jedinou projektovanou verzi řady A310, která se nikdy nedostala do sériové výroby, protože aerolinie preferovaly univerzálnost verze -200.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Hapag_Lloyd_Airbus_A310_D-AHLD.jpg',
    authorName: 'Christian Volpati / Wikimedia Commons',
    specs: {
      capacityMax: 245,
      capacityTypical: '190 - 220 (2 třídy)',
      rangeKm: 3700,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 43.9,
      lengthM: 46.66,
      heightM: 15.8,
      fuselageWidthM: 5.64,
      wingAreaM2: 219.0,
      mtowTonnes: 121.0,
      engineCount: 2,
      engineType: 'Pratt & Whitney JT9D-7R4 / General Electric CF6-80A',
      firstFlightYear: 1982,
    }
  },
  {
    id: 'airbus-a310-200',
    name: 'Airbus A310-200',
    modelSeries: 'A310 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'První sériově vyráběný model řady A310, který vstoupil do služby v roce 1983 u německé Lufthansy a švýcarského Swissairu. Tento letoun představil v té době revoluční kokpit bez palubního inženýra s obrazovkovými displeji (Glass Cockpit) a byl specifický svými špičkovými aerodynamickými vlastnostmi pro středně dlouhé trasy.',
    uniqueness: 'Klíčový model, který položil základy pro zavedení standardního dvoučlenného kokpitu do všech budoucích širokotrupých letadel Airbus.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Hapag_Lloyd_Airbus_A310_D-AHLD.jpg',
    authorName: 'Christian Volpati / Wikimedia Commons',
    specs: {
      capacityMax: 280,
      capacityTypical: '190 - 240 (3 třídy)',
      rangeKm: 6800,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 43.9,
      lengthM: 46.66,
      heightM: 15.8,
      fuselageWidthM: 5.64,
      wingAreaM2: 219.0,
      mtowTonnes: 142.0,
      engineCount: 2,
      engineType: 'Pratt & Whitney JT9D / General Electric CF6',
      firstFlightYear: 1982,
    }
  },
  {
    id: 'airbus-a310-300',
    name: 'Airbus A310-300',
    modelSeries: 'A310 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nejprodávanější verze A310 s podstatně prodlouženým doletem a zvýšenou vzletovou hmotností. Poprvé vzlétla roku 1985 a přinesla revoluční technologické vylepšení jako přídavnou nádrž v ocasu a winglety (Wingtip fences) na koncích křídel pro snížení spotřeby paliva a odporu vzduchu. Byl vyhledáván i pro přelety Atlantiku.',
    uniqueness: 'První letadlo Airbusu, které jako standard zavedlo palivovou nádrž v horizontálním stabilizátoru (ocasu) pro aktivní řízení vyvážení letadla během letu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Hapag_Lloyd_Airbus_A310_D-AHLD.jpg',
    authorName: 'Christian Volpati / Wikimedia Commons',
    specs: {
      capacityMax: 280,
      capacityTypical: '190 - 240 (3 třídy)',
      rangeKm: 9600,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 43.9,
      lengthM: 46.66,
      heightM: 15.8,
      fuselageWidthM: 5.64,
      wingAreaM2: 219.0,
      mtowTonnes: 164.0,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW4000 / General Electric CF6-80C2',
      firstFlightYear: 1985,
    }
  },
  {
    id: 'airbus-a320-100',
    name: 'Airbus A320-100',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Původní verze modelu A320. Bylo vyrobeno pouhých 21 kusů, především pro Air France a British Airways. Na rozdíl od verze -200 neměla tato verze charakteristické winglety (Wingtip fences) a měla menší palivové nádrže a nižší vzletovou hmotnost.',
    uniqueness: 'Jediná verze řady A320, která zcela postrádala winglety na koncích křídel a byla vyrobena ve velmi omezeném počtu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 180,
      capacityTypical: '150 (2 třídy)',
      rangeKm: 4800,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 33.91,
      lengthM: 37.57,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.4,
      mtowTonnes: 68.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-5A1',
      firstFlightYear: 1987,
    }
  },
  {
    id: 'airbus-a320-200',
    name: 'Airbus A320-200',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Hlavní produkční verze klasické generace A320. Přidala winglety (wingtip fences) a zvýšenou celkovou vzletovou hmotnost spolu se zvětšenými palivovými nádržemi, což z ní udělalo globální bestseller na krátkých a středních tratích.',
    uniqueness: 'Nejprodávanější model klasické generace, definující parametry nízkonákladového letectví po celém světě.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 180,
      capacityTypical: '150 (2 třídy)',
      rangeKm: 6100,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 34.10,
      lengthM: 37.57,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 78.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-5B / IAE V2527',
      firstFlightYear: 1988,
    }
  },
  {
    id: 'airbus-a320-a321-100',
    name: 'Airbus A321-100',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Prodloužená verze původního A320 nabízející vyšší kapacitu až pro 220 cestujících. Verze -100 však trpěla kratším doletem kvůli absenci dodatečných palivových nádrží, které by kompenzovaly zvýšenou hmotnost delšího trupu.',
    uniqueness: 'První prodloužená varianta A320 vyvinutá v německém Hamburku namísto francouzského Toulouse.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 220,
      capacityTypical: '185 (2 třídy)',
      rangeKm: 4300,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 34.10,
      lengthM: 44.51,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 83.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-5B / IAE V2530',
      firstFlightYear: 1993,
    }
  },
  {
    id: 'airbus-a320-a321-200',
    name: 'Airbus A321-200',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Vylepšená verze prodlouženého A321 se zvýšenou vzletovou hmotností a dodatečnými palivovými nádržemi umístěnými v nákladovém prostoru. To umožnilo plnohodnotný transkontinentální dolet se zachováním vysoké kapacity.',
    uniqueness: 'Nabízí skvělý dolet na středních tratích, což z něj dělá ideální stroj pro vytížené charterové a linkové lety.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 220,
      capacityTypical: '185 (2 třídy)',
      rangeKm: 5600,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 34.10,
      lengthM: 44.51,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 93.5,
      engineCount: 2,
      engineType: 'CFM International CFM56-5B / IAE V2533',
      firstFlightYear: 1996,
    }
  },
  {
    id: 'airbus-a320-a319-100',
    name: 'Airbus A319-100',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Zkrácená verze základního A320 (o cca 3,73 metru). Díky menšímu trupu a stejné ploše křídel a palivovým nádržím nabízí vynikající dolet a skvělé výkony na vysoko položených letištích nebo při startech za vysokých teplot.',
    uniqueness: 'Mimořádně univerzální letoun, který si oblíbily zejména společnosti jako EasyJet pro jeho flexibilitu a spolehlivost.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 156,
      capacityTypical: '124 (2 třídy)',
      rangeKm: 6950,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 34.10,
      lengthM: 33.84,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 75.5,
      engineCount: 2,
      engineType: 'CFM International CFM56-5B / IAE V2524',
      firstFlightYear: 1995,
    }
  },
  {
    id: 'airbus-a320-a319-lr',
    name: 'Airbus A319LR',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Dálková verze řady A319 se čtyřmi přídavnými palivovými nádržemi v nákladovém prostoru. Často se provozuje v luxusní celoobchodní konfiguraci (All-Business-Class) pro prestižní transatlantické lety privátního i linkového charakteru.',
    uniqueness: 'Schopnost létat na dálkových mezikontinentálních trasách s doletem přes 8 300 km při zachování nízkých provozních nákladů úzkotrupého letadla.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 48,
      capacityTypical: '48 (celoobchodní)',
      rangeKm: 8300,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 34.10,
      lengthM: 33.84,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 75.5,
      engineCount: 2,
      engineType: 'CFM International CFM56-5B',
      firstFlightYear: 2003,
    }
  },
  {
    id: 'airbus-a320-a318-100',
    name: 'Airbus A318-100',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Regionální (Regional)',
    description: 'Nejmenší "kapesní" verze rodiny A320 přezdívaná "Baby Bus" (zkrácená o 6 metrů oproti A320). Je určena pro linky s menší hustotou provozu a má unikátní certifikaci pro strmé přiblížení na letiště London City.',
    uniqueness: 'Nejmenší komerční letadlo vyrobené konsorciem Airbus, vybavené zvětšenou svislou ocasní plochou kvůli stabilitě extrémně krátkého trupu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 132,
      capacityTypical: '107 (2 třídy)',
      rangeKm: 5750,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 34.10,
      lengthM: 31.44,
      heightM: 12.51,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 68.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-5B / Pratt & Whitney PW6000',
      firstFlightYear: 2002,
    }
  },
  {
    id: 'airbus-a320-neo',
    name: 'Airbus A320neo',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Novou generaci legendárního A320 s moderními úspornými motory (New Engine Option) a velkými zkosenými winglety typu "Sharklets". Poskytuje až o 20 % nižší spotřebu paliva a výrazně tišší provoz kabiny i okolí letišť.',
    uniqueness: 'Nejrychleji prodávané letadlo v dějinách civilního letectví, které stanovilo nový ekologický i ekonomický standard pro 21. století.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 194,
      capacityTypical: '165 (2 třídy)',
      rangeKm: 6500,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 35.80,
      lengthM: 37.57,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 79.0,
      engineCount: 2,
      engineType: 'CFM International Leap-1A / Pratt & Whitney PW1100G',
      firstFlightYear: 2014,
    }
  },
  {
    id: 'airbus-a320-a321-neo',
    name: 'Airbus A321neo',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejmodernější a největší verze z řady "neo". S mimořádnou kapacitou až 244 cestujících a prodlouženým doletem začíná postupně nahrazovat na mnoha dálkových linkách i starší širokotrupé letouny, což mění ekonomiku dálkových letů.',
    uniqueness: 'Umožňuje nízkonákladový model dálkových letů přes Atlantický oceán díky kombinaci skvělého doletu a obrovské kapacity jednohorizontální kabiny.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 244,
      capacityTypical: '206 (2 třídy)',
      rangeKm: 7400,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 35.80,
      lengthM: 44.51,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 97.0,
      engineCount: 2,
      engineType: 'CFM International Leap-1A / Pratt & Whitney PW1100G',
      firstFlightYear: 2016,
    }
  },
  {
    id: 'airbus-a320-a319-neo',
    name: 'Airbus A319neo',
    modelSeries: 'A320 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejnovější modernizovaná verze řady A319 s motory nové generace. Díky svému menšímu trupu a vylepšenému pohonu vykazuje skvělé letové parametry ve vysokohorských podmínkách a extrémních teplotách, přičemž nabízí rekordní dolet ve své podkategorii.',
    uniqueness: 'Nabízí nejledší dolet z celé rodiny A320neo při zachování vynikající schopnosti operovat na letištích s náročnými drahami.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Airbus_A320-214%2C_British_Airways_JP6774635.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 160,
      capacityTypical: '136 (2 třídy)',
      rangeKm: 6850,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.78,
      wingspanM: 35.80,
      lengthM: 33.84,
      heightM: 11.76,
      fuselageWidthM: 3.95,
      wingAreaM2: 122.6,
      mtowTonnes: 75.5,
      engineCount: 2,
      engineType: 'CFM International Leap-1A / Pratt & Whitney PW1100G',
      firstFlightYear: 2017,
    }
  },
  {
    id: 'airbus-a330-300',
    name: 'Airbus A330-300',
    modelSeries: 'A330 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Základní a delší verze původní řady A330, která vzlétla poprvé v roce 1992. Tento dvoumotorový dálkový letoun s širokým trupem nabízí výtečnou přepravní kapacitu na středních až dlouhých tratích a stal se nesmírně oblíbeným mezi aerolinkami po celém světě díky skvělé ekonomice provozu.',
    uniqueness: 'První model řady A330, který byl navržen jako alternativa ke starším třímotorovým letadlům DC-10 a L-1011.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Airbus_A330-223%2C_Swiss_International_Air_Lines_JP6855146.jpg',
    authorName: 'Alan Lebeda / Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '277 (3 třídy)',
      rangeKm: 11750,
      cruiseSpeedKmh: 871,
      cruiseMach: 0.82,
      wingspanM: 60.3,
      lengthM: 63.69,
      heightM: 16.83,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 242.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent 700 / Pratt & Whitney PW4000 / GE CF6',
      firstFlightYear: 1992,
    }
  },
  {
    id: 'airbus-a330-200',
    name: 'Airbus A330-200',
    modelSeries: 'A330 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Zkrácená verze modelu A330-300 s podstatně prodlouženým doletem a větší palivovou nádrží. Byla představena v roce 1998 jako přímá odpověď na konkurenční Boeing 767-300ER. Díky excelentnímu doletu a optimální velikosti je velmi populární na méně frekventovaných, avšak mimořádně dlouhých mezikontinentálních linkách.',
    uniqueness: 'Vyšší vertikální stabilizátor (ocas) oproti verzi -300 pro kompenzaci kratšího trupu a splnění přísných aerodynamických standardů.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Airbus_A330-223%2C_Swiss_International_Air_Lines_JP6855146.jpg',
    authorName: 'Alan Lebeda / Wikimedia Commons',
    specs: {
      capacityMax: 406,
      capacityTypical: '247 (3 třídy)',
      rangeKm: 13450,
      cruiseSpeedKmh: 871,
      cruiseMach: 0.82,
      wingspanM: 60.3,
      lengthM: 58.82,
      heightM: 17.39,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 242.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent 700 / Pratt & Whitney PW4000 / GE CF6',
      firstFlightYear: 1997,
    }
  },
  {
    id: 'airbus-a330-200f',
    name: 'Airbus A330-200F',
    modelSeries: 'A330 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Čistě nákladní širokotrupé letadlo střední až velké kapacity, odvozené z úspěšné osobní verze A330-200. Nabízí vynikající flexibilitu nákladové kapacity s hlavním a dolním palubním nakládacím systémem. Vyznačuje se upravenou přední podvozkovou nohou, která vyrovnává typický sklon letadla na zemi pro usnadnění nakládky cargo palet.',
    uniqueness: 'Má unikátní "břišní hrb" v přední části podvozku, který mechanicky zvedá příď letadla na zemi do vodorovné polohy pro snadnější manipulaci s nákladem.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Airbus_A330-223%2C_Swiss_International_Air_Lines_JP6855146.jpg',
    authorName: 'Alan Lebeda / Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (až 70 tun)',
      rangeKm: 7400,
      cruiseSpeedKmh: 871,
      cruiseMach: 0.82,
      wingspanM: 60.30,
      lengthM: 58.82,
      heightM: 16.90,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 233.0,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW4000 / Rolls-Royce Trent 700',
      firstFlightYear: 2009,
    }
  },
  {
    id: 'airbus-a330-900neo',
    name: 'Airbus A330-900neo',
    modelSeries: 'A330 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Modernizovaná dálková verze nové generace s motory nové koncepce (New Engine Option). Vychází z rozměrů verze A330-300, přičemž přináší moderní křídlo inspirované typem A350 s novými elegantními zakřivenými winglety, novou kabinu Airspace a vysoce efektivní motory Rolls-Royce Trent 7000, které snižují spotřebu o 14 %.',
    uniqueness: 'Disponuje pokročilým rozpětím 64 metrů se speciálními kompozitními zaoblenými konci křídel optimalizujícími odpor vzduchu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Airbus_A330-223%2C_Swiss_International_Air_Lines_JP6855146.jpg',
    authorName: 'Alan Lebeda / Wikimedia Commons',
    specs: {
      capacityMax: 460,
      capacityTypical: '287 (3 třídy)',
      rangeKm: 13330,
      cruiseSpeedKmh: 871,
      cruiseMach: 0.82,
      wingspanM: 64.0,
      lengthM: 63.69,
      heightM: 16.79,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 251.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent 7000',
      firstFlightYear: 2017,
    }
  },
  {
    id: 'airbus-a330-800neo',
    name: 'Airbus A330-800neo',
    modelSeries: 'A330 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Kratší varianta z modernizované rodiny "neo", vycházející z trupu dřívějšího úspěšného modelu A330-200. Nabízí extrémně dlouhý transkontinentální dolet dosahující až 15 090 km. Ačkoliv je z rodiny komerčně nejméně prodávaný, představuje technologickou špičku pro dálkové nesmírně dlouhé trasy s menší hustotou cestujících.',
    uniqueness: 'Dosahuje jednoho z nejdelších doletů mezi širokotrupými dvoumotorovými letadly střední velikosti bez nutnosti pomocných nádrží.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/22/Airbus_A330-223%2C_Swiss_International_Air_Lines_JP6855146.jpg',
    authorName: 'Alan Lebeda / Wikimedia Commons',
    specs: {
      capacityMax: 406,
      capacityTypical: '220 - 260 (3 třídy)',
      rangeKm: 15090,
      cruiseSpeedKmh: 871,
      cruiseMach: 0.82,
      wingspanM: 64.0,
      lengthM: 58.82,
      heightM: 17.39,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 251.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent 7000',
      firstFlightYear: 2018,
    }
  },
  {
    id: 'airbus-a340-200',
    name: 'Airbus A340-200',
    modelSeries: 'A340 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Kratší verze původního dálkového čtyřmotorového letounu A340, vyvinutá souběžně s větší řadou -300. Bylo jich vyrobeno pouze 28 kusů, především z důvodu vysoké spotřeby čtyř motorů oproti nastupujícím dvoumotorovým letadlům. Nabízel však mimořádný dolet a otevíral nové velmi dlouhé linky.',
    uniqueness: 'Nejkratší a současně komerčně nejméně úspěšná osobní verze rodiny A340, která měla díky nízké hmotnosti a velkým nádržím skvělý dolet.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Airbus_A340-313%2C_Lufthansa_JP6853240.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 420,
      capacityTypical: '261 (3 třídy)',
      rangeKm: 15000,
      cruiseSpeedKmh: 881,
      cruiseMach: 0.82,
      wingspanM: 60.30,
      lengthM: 59.39,
      heightM: 16.70,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 275.0,
      engineCount: 4,
      engineType: 'CFM International CFM56-5C',
      firstFlightYear: 1992,
    }
  },
  {
    id: 'airbus-a340-300',
    name: 'Airbus A340-300',
    modelSeries: 'A340 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Základní a nejprodávanější klasická verze řady A340. Tento dálkový čtyřmotorový dálkový obr vzlétl v roce 1991 a stal se populárním u společností jako Lufthansa či Air France. Nabízel ideální kapacitu pro zaoceánské dálkové lety předtím, než uvolnění standardů ETOPS umožnilo dálkové lety dvoumotorovým strojům.',
    uniqueness: 'Byl navržen jako dálkový čtyřmotorový sourozenec dvoumotorového A330, se kterým sdílel téměř totožný trup, křídla a avioniku kokpitu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Airbus_A340-313%2C_Lufthansa_JP6853240.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '295 (3 třídy)',
      rangeKm: 13700,
      cruiseSpeedKmh: 881,
      cruiseMach: 0.82,
      wingspanM: 60.30,
      lengthM: 63.69,
      heightM: 16.91,
      fuselageWidthM: 5.64,
      wingAreaM2: 361.6,
      mtowTonnes: 276.5,
      engineCount: 4,
      engineType: 'CFM International CFM56-5C4',
      firstFlightYear: 1991,
    }
  },
  {
    id: 'airbus-a340-500',
    name: 'Airbus A340-500',
    modelSeries: 'A340 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Prodloužená dálková varianta druhé generace s výrazně zvětšeným rozpětím a novými motory Rolls-Royce Trent 500. Ve své době nesel titul komerčního letadla s nejdelším doletem na světě (přes 16 000 km) a pilotoval historicky nejdelší nepřetržité lety mezi Singapurem a New Yorkem.',
    uniqueness: 'Držel rekord v nejdelším doletu komerčních letadel, což umožňovalo bez mezipřistání spojit téměř jakákoli dvě místa na zeměkouli.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Airbus_A340-313%2C_Lufthansa_JP6853240.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 375,
      capacityTypical: '293 (3 třídy)',
      rangeKm: 16020,
      cruiseSpeedKmh: 896,
      cruiseMach: 0.83,
      wingspanM: 63.45,
      lengthM: 67.93,
      heightM: 17.28,
      fuselageWidthM: 5.64,
      wingAreaM2: 437.0,
      mtowTonnes: 380.0,
      engineCount: 4,
      engineType: 'Rolls-Royce Trent 553',
      firstFlightYear: 2002,
    }
  },
  {
    id: 'airbus-a340-600',
    name: 'Airbus A340-600',
    modelSeries: 'A340 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Největší, nejdelší a nejvýkonnější osobní verze řady A340. S délkou přes 75 metrů byla po dlouhou dobu nejdelším osobním dopravním letadlem na světě, než ji překonal Boeing 747-8. Sloužila jako kapacitní náhrada za starší Boeingy 747 s modernějším komfortem kabiny.',
    uniqueness: 'Jeho extrémně štíhlý a dlouhý trup působil při vzletu neuvěřitelně elegantním dojmem a v kooperaci se čtyřmi masivními motory Rolls-Royce tvořil vrchol evropské konstrukční školy začátku 21. století.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Airbus_A340-313%2C_Lufthansa_JP6853240.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 475,
      capacityTypical: '380 (3 třídy)',
      rangeKm: 14450,
      cruiseSpeedKmh: 896,
      cruiseMach: 0.83,
      wingspanM: 63.45,
      lengthM: 75.36,
      heightM: 17.29,
      fuselageWidthM: 5.64,
      wingAreaM2: 437.0,
      mtowTonnes: 380.0,
      engineCount: 4,
      engineType: 'Rolls-Royce Trent 556',
      firstFlightYear: 2001,
    }
  },
  {
    id: 'airbus-a350-900',
    name: 'Airbus A350-900',
    modelSeries: 'A350 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Základní a nejprodávanější verze řady A350 XWB, která vstoupila do služby v roce 2015. Tento mimořádně efektivní dvoumotorový dálkový letoun s širokým trupem tvoří páteř moderních dálkových flotil díky skvělé ekonomice provozu, ultra tiché kabině a rozsáhlému využití kompozitních materiálů.',
    uniqueness: 'První verze rodiny A350, která zavedla bionické křídlo měnící profil za letu a charakteristické černé olemování oken kokpitu ("Mask of Zorro").',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Airbus_A350-941%2C_Finnair_JP8119156.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '300 - 350 (3 třídy)',
      rangeKm: 15300,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 64.75,
      lengthM: 66.80,
      heightM: 17.05,
      fuselageWidthM: 5.96,
      wingAreaM2: 443.0,
      mtowTonnes: 283.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent XWB-84',
      firstFlightYear: 2013,
    }
  },
  {
    id: 'airbus-a350-1000',
    name: 'Airbus A350-1000',
    modelSeries: 'A350 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Prodloužená verze řady A350 (o cca 7 metrů oproti -900). Pro zvládnutí vyšší hmotnosti a kapacity je vybaven silnějšími motory, upravenou odtokovou hranou křídla a unikátním šestikolým hlavním podvozkem. Je navržen jako vysoce efektivní přímá náhrada za starší a větší Boeingy 777-300ER.',
    uniqueness: 'Největší člen rodiny A350 se šesti koly na každé hlavní podvozkové noze namísto čtyř, nutných pro rozprostření zátěže při vzletu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Airbus_A350-941%2C_Finnair_JP8119156.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 480,
      capacityTypical: '350 - 410 (3 třídy)',
      rangeKm: 16100,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 64.75,
      lengthM: 73.79,
      heightM: 17.08,
      fuselageWidthM: 5.96,
      wingAreaM2: 443.0,
      mtowTonnes: 319.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent XWB-97',
      firstFlightYear: 2016,
    }
  },
  {
    id: 'airbus-a350-900ulr',
    name: 'Airbus A350-900ULR',
    modelSeries: 'A350 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Ultra dálková verze (Ultra Long Range) odvozená z modelu -900. Díky modifikovanému palivovému systému a vyšší maximální vzletové hmotnosti dokáže bez mezipřistání uletět až 18 000 km. Provozují ji především Singapore Airlines na nejdelších komerčních linkách světa ze Singapuru do New Yorku.',
    uniqueness: 'Schopnost nepřetržitého letu po dobu přes 20 hodin bez nutnosti instalace dodatečných palivových nádrží v nákladovém prostoru, pouze optimalizací stávajícího objemu křídel.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Airbus_A350-941%2C_Finnair_JP8119156.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 173,
      capacityTypical: '161 (Premium-only)',
      rangeKm: 18000,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 64.75,
      lengthM: 66.80,
      heightM: 17.05,
      fuselageWidthM: 5.96,
      wingAreaM2: 443.0,
      mtowTonnes: 280.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent XWB-84',
      firstFlightYear: 2018,
    }
  },
  {
    id: 'airbus-a350f',
    name: 'Airbus A350F',
    modelSeries: 'A350 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Plně nákladní verze nové generace postavená s rozsáhlým využitím kompozitů. Nabízí moderní a vysoce efektivní letové vlastnosti, sníženou spotřebu paliva až o 40 % oproti starším typům a velké břišní i boční cargo dveře.',
    uniqueness: 'Jediné cargo letadlo, které plně splňuje nejnovější nejpřísnější emisní limity ICAO pro rok 2028 díky své ultralehké kompozitní konstrukci.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Airbus_A350-941%2C_Finnair_JP8119156.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (až 109 tun)',
      rangeKm: 8700,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 64.75,
      lengthM: 70.80,
      heightM: 17.05,
      fuselageWidthM: 5.96,
      wingAreaM2: 443.0,
      mtowTonnes: 319.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent XWB-97',
      firstFlightYear: 2024,
    }
  },
  {
    id: 'airbus-a380-800',
    name: 'Airbus A380-800',
    modelSeries: 'A380 Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Největší osobní dopravní letadlo na světě, přezdívané „Superjumbo“. S plně dvoupatrovou kabinou nabízí ohromující prostor, jenž luxusní letecké společnosti využily k vybudování barů, sprchových koutů či soukromých apartmánů. Přestože byla výroba ukončena, zůstává symbolem gigantické letecké éry.',
    uniqueness: 'Jeho celková plocha křídel je tak obrovská, že by na ni bylo možné zaparkovat téměř 70 osobních automobilů, což dává stroji perfektní vztlak.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Airbus_A380-841%2C_Singapore_Airlines_JP7515089.jpg',
    authorName: 'Ryan Hothersall / Wikimedia Commons',
    specs: {
      capacityMax: 853,
      capacityTypical: '525 (3 třídy)',
      rangeKm: 14800,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 79.75,
      lengthM: 72.72,
      heightM: 24.09,
      fuselageWidthM: 7.14,
      wingAreaM2: 845.0,
      mtowTonnes: 575.0,
      engineCount: 4,
      engineType: 'Engine Alliance GP7200 / Rolls-Royce Trent 900',
      firstFlightYear: 2005,
    }
  },
  {
    id: 'airbus-beluga-a300-600st',
    name: 'Airbus A300-600ST Beluga',
    modelSeries: 'Beluga Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Unikátní nákladní letadlo určené výhradně pro převoz nadrozměrných leteckých komponentů (např. celých křídel či částí trupů) mezi jednotlivými evropskými továrnami Airbusu. Otevřená příď a ohromující nafouklý horní trup mu vysloužily trefnou přezdívku podle sněhobílé arktické velryby Belugy.',
    uniqueness: 'Má jeden z nejobjemnějších nákladových prostorů na světě, který mu umožňuje spolknout v podstatě celou sekci trupu nového dálkového Airbusu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Airbus_A300-608ST_Beluga_at_Southend_Airport%2C_April_2004.jpg',
    authorName: 'Aviation Commons / Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (až 47 tun)',
      rangeKm: 4600,
      cruiseSpeedKmh: 737,
      cruiseMach: 0.70,
      wingspanM: 44.84,
      lengthM: 56.15,
      heightM: 17.24,
      fuselageWidthM: 7.7,
      wingAreaM2: 260.0,
      mtowTonnes: 155.0,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2',
      firstFlightYear: 1994,
    }
  },
  {
    id: 'airbus-belugaxl',
    name: 'Airbus BelugaXL',
    modelSeries: 'Beluga Family',
    manufacturer: 'Airbus',
    country: 'Evropská unie',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nová generace obřího nákladního letadla, postavená na bázi modernějšího dálkového typu Airbus A330-200. S výrazným nárůstem kapacity o 30 % oproti předchozí verzi Beluga ST umožňuje přepravovat najednou hned dvě křídla pro nejnovější Airbus A350 XWB namísto jednoho. Je snadno rozpoznatelná díky veselé "usměvavé" malbě velryby na trupu.',
    uniqueness: 'Největší vnitřní průměr nákladového prostoru ze všech cargo letadel na světě (8,8 metru) a unikátní usmívající se grafika Belugy navržená samotnými zaměstnanci Airbusu.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Airbus_Beluga_XL_F-WBXL_%2845618491754%29.jpg',
    authorName: 'Aviation Commons / Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (až 50,5 tun)',
      rangeKm: 4000,
      cruiseSpeedKmh: 737,
      cruiseMach: 0.69,
      wingspanM: 60.3,
      lengthM: 63.1,
      heightM: 18.9,
      fuselageWidthM: 8.8,
      wingAreaM2: 361.6,
      mtowTonnes: 227.0,
      engineCount: 2,
      engineType: 'Rolls-Royce Trent 700',
      firstFlightYear: 2018,
    }
  },

  // BOEING MODELS
  {
    id: 'boeing-707-120',
    name: 'Boeing 707-120',
    modelSeries: '707 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'Původní produkční verze legendární rodiny Boeingu 707, navržená především pro vnitrostátní a kontinentální americké lety. Je poháněna proudovými motory Pratt & Whitney JT3C s charakteristickým vodním vstřikováním pro zvýšení tahu při vzletu.',
    uniqueness: 'Pravě tato verze provedla 26. října 1958 ikonický první pravidelný let společnosti Pan Am přes Atlantik z New Yorku do Paříže.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Boeing_707-121_N707PA_Pan_Am_LHR_07.59_edited-2.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 189,
      capacityTypical: '110 (2 třídy)',
      rangeKm: 6200,
      cruiseSpeedKmh: 917,
      cruiseMach: 0.84,
      wingspanM: 39.88,
      lengthM: 44.22,
      heightM: 12.93,
      fuselageWidthM: 3.76,
      wingAreaM2: 226.3,
      mtowTonnes: 116.5,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT3C-6',
      firstFlightYear: 1957,
    }
  },
  {
    id: 'boeing-707-220',
    name: 'Boeing 707-220',
    modelSeries: '707 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'Speciální varianta využívající totožný drak s verzí -120, ale vybavená silnějšími proudovými motory Pratt & Whitney JT4A. Byla zkonstruována speciálně pro provoz na letištích s vysokou nadmořskou výškou a v horkých klimatických podmínkách (hot & high).',
    uniqueness: 'Je to jedna z nejvzácnějších verzí - bylo vyrobeno pouhých 5 exemplářů, které zakoupila a exkluzivně provozovala společnost Braniff International Airways.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Boeing_707-227_Braniff_N7072_DAL_1969.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 189,
      capacityTypical: '110 (2 třídy)',
      rangeKm: 5800,
      cruiseSpeedKmh: 917,
      cruiseMach: 0.84,
      wingspanM: 39.88,
      lengthM: 44.22,
      heightM: 12.93,
      fuselageWidthM: 3.76,
      wingAreaM2: 226.3,
      mtowTonnes: 117.0,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT4A-3',
      firstFlightYear: 1959,
    }
  },
  {
    id: 'boeing-707-320',
    name: 'Boeing 707-320',
    modelSeries: '707 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'Výrazně zvětšená a dálková verze (Intercontinental). Má prodloužený trup, větší rozteč sedadel pro mezikontinentální komfort, přepracované a prodloužené křídlo a modernější, úspornější dvouproudové motory Pratt & Whitney JT3D (u verze 320B/C).',
    uniqueness: 'Stala se zdaleka nejprodávanější a nejúspěšnější variantou celé rodiny 707, která propojila kontinenty bez nutnosti mezipřistání k tankování.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Boeing_707-321B%2C_Pan_American_World_Airways_%28Pan_Am%29_JP6905581.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 219,
      capacityTypical: '141 (2 třídy)',
      rangeKm: 9300,
      cruiseSpeedKmh: 973,
      cruiseMach: 0.84,
      wingspanM: 44.42,
      lengthM: 46.61,
      heightM: 12.93,
      fuselageWidthM: 3.76,
      wingAreaM2: 294.0,
      mtowTonnes: 151.3,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT3D-3',
      firstFlightYear: 1959,
    }
  },
  {
    id: 'boeing-720',
    name: 'Boeing 720',
    modelSeries: '720 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'Odlehčená a zkrácená verze Boeingu 707 vyvinutá pro kratší a střední tratě a provoz z méně vybavených letišť s kratšími dráhami. Původně byla vyvíjena pod označením 707-020, drak získal inovované náběžné hrany křídel pro vyšší rychlosti.',
    uniqueness: 'Měla nejnižší prázdnou hmotnost ze všech čtyřmotorových proudových dopravních letadel Boeing a vynikala vynikajícím poměrem výkonu k hmotnosti.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Boeing_720-047B%2C_Western_Airlines_JP6131346.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 156,
      capacityTypical: '112 (2 třídy)',
      rangeKm: 4500,
      cruiseSpeedKmh: 980,
      cruiseMach: 0.85,
      wingspanM: 39.88,
      lengthM: 41.50,
      heightM: 12.65,
      fuselageWidthM: 3.76,
      wingAreaM2: 234.0,
      mtowTonnes: 104.3,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT3D-1',
      firstFlightYear: 1959,
    }
  },
  {
    id: 'boeing-717-200',
    name: 'Boeing 717-200',
    modelSeries: '717 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Regionální (Regional)',
    description: 'Kompaktní úzkotrupý letoun navržený speciálně pro vysokofrekvenční krátké vnitrostátní a regionální linky. Původně byl vyvíjen společnost McDonnell Douglas jako MD-95, ale po akvizici firmy přejmenován na Boeing 717. Charakterizuje se umístěním motorů na zádi a koncovými plochami křídel ve tvaru T.',
    uniqueness: 'Je mimořádně oblíben pro svou robustnost a extrémně rychlé letištní obrátky na krátkých letech s mnoha cykly denně.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Boeing_717-200%2C_Hawaiian_Airlines_JP8214227.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 134,
      capacityTypical: '106 (2 třídy)',
      rangeKm: 3820,
      cruiseSpeedKmh: 822,
      cruiseMach: 0.77,
      wingspanM: 28.4,
      lengthM: 37.8,
      heightM: 8.92,
      fuselageWidthM: 3.34,
      wingAreaM2: 92.9,
      mtowTonnes: 54.9,
      engineCount: 2,
      engineType: 'Rolls-Royce BR700',
      firstFlightYear: 1998,
    }
  },
  {
    id: 'boeing-727-100',
    name: 'Boeing 727-100',
    modelSeries: '727 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'První a kratší produkční verze legendárního třímotorového letounu Boeing 727, která poprvé vzlétla v roce 1963. Byla navržena pro kratší vzletové a přistávací dráhy a stala se velmi populární u regionálních i mezinárodních dopravců po celém světě.',
    uniqueness: 'Byl navržen tak, aby mohl bezpečně operovat i z letišť s kratšími drahami, což mu otevřelo cestu do mnoha menších měst.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Boeing_727-100_United_Airlines_N7001U.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 131,
      capacityTypical: '94 (2 třídy)',
      rangeKm: 4300,
      cruiseSpeedKmh: 870,
      cruiseMach: 0.82,
      wingspanM: 32.92,
      lengthM: 40.59,
      heightM: 10.36,
      fuselageWidthM: 3.76,
      wingAreaM2: 157.9,
      mtowTonnes: 77.1,
      engineCount: 3,
      engineType: 'Pratt & Whitney JT8D-1',
      firstFlightYear: 1963,
    }
  },
  {
    id: 'boeing-727-200',
    name: 'Boeing 727-200',
    modelSeries: '727 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'Prodloužená verze úspěšného třímotorového letounu Boeing 727, která byla představena v roce 1967. Nabídla výrazně vyšší kapacitu cestujících a v 70. a 80. letech se stala oporou vnitrostátních letů v USA.',
    uniqueness: 'S více než 1200 vyrobenými kusy se jednalo o vůbec nejprodávanější verzi celé rodiny letounů Boeing 727.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Boeing_727-227%2C_Braniff_International_Airways_JP6678224.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 189,
      capacityTypical: '134 (2 třídy)',
      rangeKm: 4720,
      cruiseSpeedKmh: 870,
      cruiseMach: 0.82,
      wingspanM: 32.92,
      lengthM: 46.68,
      heightM: 10.36,
      fuselageWidthM: 3.76,
      wingAreaM2: 157.9,
      mtowTonnes: 95.1,
      engineCount: 3,
      engineType: 'Pratt & Whitney JT8D-15',
      firstFlightYear: 1967,
    }
  },
  {
    id: 'boeing-727f',
    name: 'Boeing 727F',
    modelSeries: '727 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Historická / Nadzvuková',
    description: 'Specializovaná nákladní (Freighter) verze legendárního třímotoráku Boeing 727. Mnoho z těchto letounů bylo přestavěno z původních verzí pro cestující a sloužily po léta u velkých přepravců jako FedEx, DHL nebo UPS díky své robustnosti a spolehlivosti.',
    uniqueness: 'Byl vybaven velkými nákladovými dveřmi na levé straně trupu a zesílenou podlahou kabiny pro převoz těžkých kontejnerů.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Boeing_727-22C_FedEx_Express_JP6271970.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (Až 11 palet)',
      rangeKm: 4200,
      cruiseSpeedKmh: 860,
      cruiseMach: 0.81,
      wingspanM: 32.92,
      lengthM: 46.68,
      heightM: 10.36,
      fuselageWidthM: 3.76,
      wingAreaM2: 157.9,
      mtowTonnes: 95.1,
      engineCount: 3,
      engineType: 'Pratt & Whitney JT8D-17',
      firstFlightYear: 1983,
    }
  },
  {
    id: 'boeing-737-100',
    name: 'Boeing 737-100',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'První verze legendárního dvoumotorového úzkotrupého letounu. Vyvinuta koncem 60. let původně pro Lufthansu. Jedná se o nejkratší verzi z celé rodiny 737.',
    uniqueness: 'Vyrobilo se pouze 30 kusů této verze, než byla nahrazena úspěšnější verzí -200.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Lufthansa_Boeing_737-130_D-ABED_Uli_W_Munich.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 115,
      capacityTypical: '85 (2 třídy)',
      rangeKm: 2850,
      cruiseSpeedKmh: 817,
      cruiseMach: 0.73,
      wingspanM: 28.35,
      lengthM: 28.67,
      heightM: 11.23,
      fuselageWidthM: 3.76,
      wingAreaM2: 102.0,
      mtowTonnes: 49.9,
      engineCount: 2,
      engineType: 'Pratt & Whitney JT8D-7',
      firstFlightYear: 1967,
    }
  },
  {
    id: 'boeing-737-200',
    name: 'Boeing 737-200',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Prodloužená verze první generace (Original) s vylepšenou aerodynamikou a motory. Dosáhla velkého komerčního úspěchu po celém světě.',
    uniqueness: 'Mohl být vybaven tzv. „Unpaved Strip Kitem“ pro operování z nezpevněných (např. štěrkových) drah.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Boeing_737-200_Allf_Jetran_Air_N982UA.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 130,
      capacityTypical: '102 (2 třídy)',
      rangeKm: 3500,
      cruiseSpeedKmh: 817,
      cruiseMach: 0.73,
      wingspanM: 28.35,
      lengthM: 30.53,
      heightM: 11.23,
      fuselageWidthM: 3.76,
      wingAreaM2: 102.0,
      mtowTonnes: 52.4,
      engineCount: 2,
      engineType: 'Pratt & Whitney JT8D-9/15',
      firstFlightYear: 1967,
    }
  },
  {
    id: 'boeing-737-300',
    name: 'Boeing 737-300',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Základní model druhé generace (Classic). Přinesl revoluční dvouproudové motory CFM56, které byly výrazně tišší a úspornější.',
    uniqueness: 'Kvůli nízké světlé výšce křídla musely mít motory CFM56 charakteristický zploštělý tvar spodní části krytu (tzv. „hamster pouch“).',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Boeing_737-300_Lufthansa_D-ABED.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 149,
      capacityTypical: '128 (2 třídy)',
      rangeKm: 4200,
      cruiseSpeedKmh: 796,
      cruiseMach: 0.745,
      wingspanM: 28.88,
      lengthM: 33.4,
      heightM: 11.13,
      fuselageWidthM: 3.76,
      wingAreaM2: 105.4,
      mtowTonnes: 62.8,
      engineCount: 2,
      engineType: 'CFM International CFM56-3',
      firstFlightYear: 1984,
    }
  },
  {
    id: 'boeing-737-400',
    name: 'Boeing 737-400',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Prodloužená verze rodiny Classic, navržená k vyplnění mezery mezi 737-300 a větším 757-200. Často slouží i jako konvertovaný nákladní speciál.',
    uniqueness: 'Disponoval upraveným systémem klimatizace a zesíleným podvozkem pro těžší vzletovou hmotnost.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Boeing_737-400_Turkish_Airlines_TC-JEY.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 188,
      capacityTypical: '146 (2 třídy)',
      rangeKm: 3820,
      cruiseSpeedKmh: 796,
      cruiseMach: 0.745,
      wingspanM: 28.88,
      lengthM: 36.45,
      heightM: 11.13,
      fuselageWidthM: 3.76,
      wingAreaM2: 105.4,
      mtowTonnes: 68.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-3C',
      firstFlightYear: 1988,
    }
  },
  {
    id: 'boeing-737-500',
    name: 'Boeing 737-500',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejkratší model z řady Classic. Byl vyvinut jako moderní náhrada za starší 737-200, nabízející mnohem delší dolet a hospodárnost.',
    uniqueness: 'Byl velmi oblíbený u aerolinek pro kratší linky s nižší poptávkou, protože kombinoval nízké provozní náklady s moderní technikou Classic.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Boeing_737-522_United_Airlines_N919UA.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 132,
      capacityTypical: '110 (2 classes)',
      rangeKm: 4400,
      cruiseSpeedKmh: 796,
      cruiseMach: 0.745,
      wingspanM: 28.88,
      lengthM: 31.01,
      heightM: 11.13,
      fuselageWidthM: 3.76,
      wingAreaM2: 105.4,
      mtowTonnes: 60.5,
      engineCount: 2,
      engineType: 'CFM International CFM56-3B',
      firstFlightYear: 1989,
    }
  },
  {
    id: 'boeing-737-600',
    name: 'Boeing 737-600',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejmenší verze řady Next Generation (NG). Nahradil zastarávající model 737-500 a přímo konkuroval letounům Airbus A318.',
    uniqueness: 'O tuto nejmenší verzi NG byl poměrně malý zájem; vyrobilo se pouhých 69 kusů, převážně pro skandinávský SAS.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/43/SAS_Boeing_737-600_LN-RRP_at_Arlanda.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 130,
      capacityTypical: '110 (2 třídy)',
      rangeKm: 5648,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.785,
      wingspanM: 34.32,
      lengthM: 31.24,
      heightM: 12.57,
      fuselageWidthM: 3.76,
      wingAreaM2: 124.6,
      mtowTonnes: 66.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-7B',
      firstFlightYear: 1998,
    }
  },
  {
    id: 'boeing-737-700',
    name: 'Boeing 737-700',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'První model řady Next Generation (NG). Vycházel z modelu 737-300, obdržel však zcela nové křídlo, modernizovaný kokpit a účinnější motory.',
    uniqueness: 'Byl základem pro luxusní soukromé verze BBJ1 (Boeing Business Jet) s obrovským mezikontinentálním doletem.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Boeing_737-700_Southwest_N709SW.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 149,
      capacityTypical: '126 (2 třídy)',
      rangeKm: 6010,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.785,
      wingspanM: 34.32,
      lengthM: 33.63,
      heightM: 12.57,
      fuselageWidthM: 3.76,
      wingAreaM2: 124.6,
      mtowTonnes: 70.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-7B',
      firstFlightYear: 1997,
    }
  },
  {
    id: 'boeing-737-800',
    name: 'Boeing 737-800',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejprodávanější a nejvýznamnější model celé řady Next Generation. Stal se absolutním standardem a páteří flotil nízkonákladových gigantů jako Ryanair či Southwest Airlines.',
    uniqueness: 'Se zhruba 5000 vyrobenými kusy patří k nejrozšířenějším dopravním letounům v historii letectví.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Boeing_737-8AS%2C_Ryanair_JP7518423.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 189,
      capacityTypical: '162 (2 třídy)',
      rangeKm: 5430,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.785,
      wingspanM: 35.79,
      lengthM: 39.47,
      heightM: 12.55,
      fuselageWidthM: 3.76,
      wingAreaM2: 124.6,
      mtowTonnes: 79.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-7B27',
      firstFlightYear: 1997,
    }
  },
  {
    id: 'boeing-737-900',
    name: 'Boeing 737-900',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejdelší verze rodiny Next Generation představená v roce 2000. Poskytuje vyšší kapacitu, ale zachovala si původní konfiguraci nouzových východů, což limitovalo její plný kapacitní potenciál.',
    uniqueness: 'Trpěl omezením maximální certifikované kapacity na 189 pasažérů kvůli stejnému počtu dveří jako u verze -800.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/29/KLM_Boeing_737-900_PH-BXO.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 189,
      capacityTypical: '177 (2 třídy)',
      rangeKm: 5460,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.785,
      wingspanM: 35.79,
      lengthM: 42.11,
      heightM: 12.52,
      fuselageWidthM: 3.76,
      wingAreaM2: 124.6,
      mtowTonnes: 79.0,
      engineCount: 2,
      engineType: 'CFM International CFM56-7B',
      firstFlightYear: 2000,
    }
  },
  {
    id: 'boeing-737-900er',
    name: 'Boeing 737-900ER',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Vylepšená verze 737-900 s prodlouženým doletem (Extended Range). Obdržela přidaný pár nouzových dveří a dodatečné palivové nádrže.',
    uniqueness: 'Umožnil navýšit kapacitu na 215 cestujících a úspěšně konkuroval letounům Airbus A321.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Delta_Air_Lines_Boeing_737-900ER_N830DN_at_LAX.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 215,
      capacityTypical: '180 (2 třídy)',
      rangeKm: 5925,
      cruiseSpeedKmh: 828,
      cruiseMach: 0.785,
      wingspanM: 35.79,
      lengthM: 42.11,
      heightM: 12.52,
      fuselageWidthM: 3.76,
      wingAreaM2: 124.6,
      mtowTonnes: 85.1,
      engineCount: 2,
      engineType: 'CFM International CFM56-7B27',
      firstFlightYear: 2006,
    }
  },
  {
    id: 'boeing-737-max-7',
    name: 'Boeing 737 MAX 7',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Nejmenší verze nejnovější rodiny 737 MAX. Vybavena moderními motory LEAP-1B, novými winglety a vylepšenou avionikou.',
    uniqueness: 'Nabízí ze všech verzí rodiny MAX vůbec nejdelší dolet, dosahující až 7 130 km.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Boeing_737_MAX_7_N7201S_BFI.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 172,
      capacityTypical: '138 (2 třídy)',
      rangeKm: 7130,
      cruiseSpeedKmh: 839,
      cruiseMach: 0.79,
      wingspanM: 35.92,
      lengthM: 35.56,
      heightM: 12.3,
      fuselageWidthM: 3.76,
      wingAreaM2: 127.0,
      mtowTonnes: 80.3,
      engineCount: 2,
      engineType: 'CFM International LEAP-1B',
      firstFlightYear: 2018,
    }
  },
  {
    id: 'boeing-737-max-8',
    name: 'Boeing 737 MAX 8',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Základní a nejprodávanější model nejnovější generace MAX. Nabízí excelentní provozní efektivitu s nízkými emisemi a hlukovou stopou.',
    uniqueness: 'Oproti minulé generaci spotřebovává až o 16 % méně paliva na jedno sedadlo.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Southwest_Airlines_Boeing_737_MAX_8_N8710S.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 210,
      capacityTypical: '162 (2 třídy)',
      rangeKm: 6570,
      cruiseSpeedKmh: 839,
      cruiseMach: 0.79,
      wingspanM: 35.92,
      lengthM: 39.52,
      heightM: 12.3,
      fuselageWidthM: 3.76,
      wingAreaM2: 127.0,
      mtowTonnes: 82.2,
      engineCount: 2,
      engineType: 'CFM International LEAP-1B',
      firstFlightYear: 2016,
    }
  },
  {
    id: 'boeing-737-max-9',
    name: 'Boeing 737 MAX 9',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Prodloužená verze rodiny MAX nahrazující úspěšný model 737-900ER. Poskytuje skvělou ekonomiku na dálkových vnitrostátních linkách.',
    uniqueness: 'Srdcem kokpitu jsou obří displeje převzaté přímo z revolučního dálkového Boeingu 787 Dreamliner.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/United_Airlines_Boeing_737_MAX_9_N37502.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 220,
      capacityTypical: '178 (2 třídy)',
      rangeKm: 6570,
      cruiseSpeedKmh: 839,
      cruiseMach: 0.79,
      wingspanM: 35.92,
      lengthM: 42.16,
      heightM: 12.3,
      fuselageWidthM: 3.76,
      wingAreaM2: 127.0,
      mtowTonnes: 88.3,
      engineCount: 2,
      engineType: 'CFM International LEAP-1B',
      firstFlightYear: 2017,
    }
  },
  {
    id: 'boeing-737-max-10',
    name: 'Boeing 737 MAX 10',
    modelSeries: '737 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Vůbec nejdelší varianta v celé historii letounů Boeing 737. Pojme až 230 pasažérů a disponuje inovativním teleskopickým hlavním podvozkem.',
    uniqueness: 'Jeho speciálně navržený teleskopický podvozek se při vzletu prodlouží, aby se zabránilo nárazu zádě o dráhu (tailstrike).',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Boeing_737_MAX_10_N27751_BFI_2.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 230,
      capacityTypical: '188 (2 třídy)',
      rangeKm: 6110,
      cruiseSpeedKmh: 839,
      cruiseMach: 0.79,
      wingspanM: 35.92,
      lengthM: 43.8,
      heightM: 12.3,
      fuselageWidthM: 3.76,
      wingAreaM2: 127.0,
      mtowTonnes: 89.7,
      engineCount: 2,
      engineType: 'CFM International LEAP-1B',
      firstFlightYear: 2020,
    }
  },
  {
    id: 'boeing-747-100',
    name: 'Boeing 747-100',
    modelSeries: '747 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Původní verze legendární „Královny nebes“, která v roce 1969 zahájila éru velkokapacitních letadel (wide-body). Nabídla bezprecedentní rozměry, horní palubu s charakteristickým hrbem a změnila dálkovou leteckou dopravu.',
    uniqueness: 'Byl vyvinut za pouhých 29 měsíců skupinou inženýrů vedených Joem Sutterem, známých jako „The Incredibles“.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Boeing_747-121_Pan_Am_N732PA_SFO_1973.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 452,
      capacityTypical: '366 (3 třídy)',
      rangeKm: 8560,
      cruiseSpeedKmh: 893,
      cruiseMach: 0.84,
      wingspanM: 59.64,
      lengthM: 70.66,
      heightM: 19.33,
      fuselageWidthM: 6.5,
      wingAreaM2: 511.0,
      mtowTonnes: 333.4,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT9D-3A',
      firstFlightYear: 1969,
    }
  },
  {
    id: 'boeing-747-200',
    name: 'Boeing 747-200',
    modelSeries: '747 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Vylepšená verze zavedená v roce 1971 se silnějšími motory, zvýšenou maximální vzletovou hmotností a prodlouženým doletem. Vyráběla se v osobních, nákladních (F) i kombinovaných (Combi) verzích.',
    uniqueness: 'Speciálně upravené verze VC-25A slouží pod volacím znakem Air Force One jako létající úřad amerického prezidenta.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Boeing_747-200_KLM.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 452,
      capacityTypical: '366 (3 třídy)',
      rangeKm: 12150,
      cruiseSpeedKmh: 893,
      cruiseMach: 0.84,
      wingspanM: 59.64,
      lengthM: 70.66,
      heightM: 19.33,
      fuselageWidthM: 6.5,
      wingAreaM2: 511.0,
      mtowTonnes: 377.8,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT9D-7J / CF6-50',
      firstFlightYear: 1970,
    }
  },
  {
    id: 'boeing-747-300',
    name: 'Boeing 747-300',
    modelSeries: '747 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Verze představená v roce 1982, jejímž nejvýraznějším prvkem byla prodloužená horní paluba (SUD - Stretched Upper Deck). To umožnilo zvýšit kapacitu a zlepšit komfort pro cestující na horní palubě.',
    uniqueness: 'Prodloužená horní paluba zvýšila aerodynamickou účinnost letadla, což mu umožnilo létat mírně vyšší cestovní rychlostí Mach 0,85.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Boeing_747-300_Swissair.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 496,
      capacityTypical: '400 (3 třídy)',
      rangeKm: 12400,
      cruiseSpeedKmh: 907,
      cruiseMach: 0.85,
      wingspanM: 59.64,
      lengthM: 70.66,
      heightM: 19.33,
      fuselageWidthM: 6.5,
      wingAreaM2: 511.0,
      mtowTonnes: 377.8,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT9D-7R4G2 / CF6-80C2',
      firstFlightYear: 1982,
    }
  },
  {
    id: 'boeing-747-400',
    name: 'Boeing 747-400',
    modelSeries: '747 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Komerčně nejúspěšnější a nejprodávanější verze rodiny 747. Přinesla plně digitální kokpit (glass cockpit) s redukcí posádky na dva piloty, prodloužené rozpětí křídel s charakteristickými winglety a nové úsporné motory.',
    uniqueness: 'Winglety na koncích křídel o výšce 1,8 metru snížily spotřebu paliva o 4 % a staly se poznávacím znakem této generace.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Boeing_747-422_United_Airlines_N171UA_at_SFO.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 660,
      capacityTypical: '416 (3 třídy)',
      rangeKm: 13450,
      cruiseSpeedKmh: 907,
      cruiseMach: 0.85,
      wingspanM: 64.44,
      lengthM: 70.66,
      heightM: 19.41,
      fuselageWidthM: 6.5,
      wingAreaM2: 541.2,
      mtowTonnes: 396.9,
      engineCount: 4,
      engineType: 'Pratt & Whitney PW4056 / General Electric CF6-80C2 / Rolls-Royce RB211',
      firstFlightYear: 1988,
    }
  },
  {
    id: 'boeing-747sp',
    name: 'Boeing 747SP',
    modelSeries: '747 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Zkrácená verze (Special Performance) vyvinutá v polovině 70. let pro extrémně dlouhé tratě. Trup byl zkrácen o 14 metrů a ocasní plochy byly zvětšeny, což letadlu umožnilo létat výše, rychleji a s rekordním doletem.',
    uniqueness: 'Měl tak vynikající stoupavost a výškový dostup, že mohl létat nad oblačností a běžným provozem ostatních dopravních letadel.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Boeing_747SP_Iran_Air_EP-IAC_at_LHR.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 400,
      capacityTypical: '276 (3 třídy)',
      rangeKm: 12325,
      cruiseSpeedKmh: 924,
      cruiseMach: 0.87,
      wingspanM: 59.64,
      lengthM: 56.31,
      heightM: 20.1,
      fuselageWidthM: 6.5,
      wingAreaM2: 511.0,
      mtowTonnes: 317.5,
      engineCount: 4,
      engineType: 'Pratt & Whitney JT9D-7A / Rolls-Royce RB211',
      firstFlightYear: 1975,
    }
  },
  {
    id: 'boeing-747-8',
    name: 'Boeing 747-8',
    modelSeries: '747 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nejnovější a největší generace slavného čtyřmotoráku. Využívá moderní technologie ze 787 Dreamliner, včetně motorů GEnx, nového profilu křídla a prodlouženého trupu. Vyrábí se jako verze pro cestující (Intercontinental) i jako velmi žádaný Freighter (8F).',
    uniqueness: 'Jedná se o nejdelší dopravní pilotované letadlo v aktivní službě na světě, které měří bezmála 76,3 metru.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Boeing_747-8_D-ABYI_Lufthansa_%2810899388334%29.jpg',
    authorName: 'Julian Herzog / Wikimedia Commons',
    specs: {
      capacityMax: 605,
      capacityTypical: '410 (3 třídy)',
      rangeKm: 14320,
      cruiseSpeedKmh: 917,
      cruiseMach: 0.86,
      wingspanM: 68.4,
      lengthM: 76.3,
      heightM: 19.4,
      fuselageWidthM: 6.5,
      wingAreaM2: 554.0,
      mtowTonnes: 447.7,
      engineCount: 4,
      engineType: 'General Electric GEnx-2B67',
      firstFlightYear: 2010,
    }
  },
  {
    id: 'boeing-757-200',
    name: 'Boeing 757-200',
    modelSeries: '757 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'První a zdaleka nejrozšířenější pasažérská verze řady 757. Je proslulá vynikajícími letovými vlastnostmi, mimořádnou stoupavostí a schopností obsluhovat kratší letiště s vysokou nadmořskou výškou.',
    uniqueness: 'Piloti ho pro obrovský nadbytek výkonu motorů Rolls-Royce či Pratt & Whitney často přezdívají „létající raketa“.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Boeing_757-223%2C_American_Airlines_JP6529323.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 239,
      capacityTypical: '200 (2 třídy)',
      rangeKm: 7250,
      cruiseSpeedKmh: 854,
      cruiseMach: 0.80,
      wingspanM: 38.05,
      lengthM: 47.32,
      heightM: 13.56,
      fuselageWidthM: 3.76,
      wingAreaM2: 185.25,
      mtowTonnes: 115.6,
      engineCount: 2,
      engineType: 'Rolls-Royce RB211-535 / Pratt & Whitney PW2000',
      firstFlightYear: 1982,
    }
  },
    {
    id: 'boeing-757-300',
    name: 'Boeing 757-300',
    modelSeries: '757 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Výrazně prodloužená verze řady 757, která poprvé vzlétla v roce 1998. Měří přes 54 metrů a jedná se o nejdelší dvoumotorový úzkotrupý dopravní letoun, jaký byl kdy postaven.',
    uniqueness: 'Kvůli svému neobvyklému poměru extrémní délky k průměru trupu si u leteckých posádek vysloužil přezdívku „létající tužka“ (Flying Pencil).',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Boeing_757-300_Condor_D-ABON.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 295,
      capacityTypical: '243 (2 třídy)',
      rangeKm: 6290,
      cruiseSpeedKmh: 854,
      cruiseMach: 0.80,
      wingspanM: 38.05,
      lengthM: 54.47,
      heightM: 13.56,
      fuselageWidthM: 3.76,
      wingAreaM2: 185.25,
      mtowTonnes: 123.8,
      engineCount: 2,
      engineType: 'Rolls-Royce RB211-535E4B / Pratt & Whitney PW2043',
      firstFlightYear: 1998,
    }
  },
  {
    id: 'boeing-757-200pf',
    name: 'Boeing 757-200PF',
    modelSeries: '757 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Specializovaná, přímo z továrny postavená nákladní verze (Package Freighter). Byla vyvinuta speciálně pro expresní zásilkové služby jako UPS, FedEx či DHL.',
    uniqueness: 'Tento letoun nemá v kabině žádná okénka ani sedadla a je vybaven širokými předními nákladními dveřmi pro manipulaci s kontejnery.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/29/UPS_Boeing_757-200PF_N406UP.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (Až 15 palet)',
      rangeKm: 5830,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 38.05,
      lengthM: 47.32,
      heightM: 13.56,
      fuselageWidthM: 3.76,
      wingAreaM2: 185.25,
      mtowTonnes: 115.6,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW2037 / Rolls-Royce RB211',
      firstFlightYear: 1987,
    }
  },
  {
    id: 'boeing-757-200sf',
    name: 'Boeing 757-200SF',
    modelSeries: '757 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Úzkotrupá (Single-Aisle)',
    description: 'Konvertovaná nákladní verze (Special Freighter), která vznikla přestavbou vyřazených a starších standardních pasažérských letounů Boeing 757-200.',
    uniqueness: 'Díky této konverzi dostaly stovky starších pasažérských letadel nový život a staly se mimořádně efektivní součástí globálních cargo flotil.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/DHL_Boeing_757-200SF%2C_G-DHKF.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (Až 15 palet)',
      rangeKm: 5830,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 38.05,
      lengthM: 47.32,
      heightM: 13.56,
      fuselageWidthM: 3.76,
      wingAreaM2: 185.25,
      mtowTonnes: 115.6,
      engineCount: 2,
      engineType: 'Rolls-Royce RB211-535 / Pratt & Whitney PW2040',
      firstFlightYear: 2001,
    }
  },
  {
    id: 'boeing-767-200',
    name: 'Boeing 767-200',
    modelSeries: '767 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'První verze rodiny 767, která poprvé vzlétla v roce 1981. Byl navržen primárně pro vnitrostátní dálkové trasy v USA, ale později se uplatnil i na zaoceánských letech díky postupné certifikaci ETOPS.',
    uniqueness: 'Zahájil revoluci dvoupilotních širokotrupých letadel a do tehdejší doby novou úroveň standardizace kokpitu s typem 757.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Boeing_767-223_ER_N302AA_American_Airlines_Aviation_Photoblog.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 290,
      capacityTypical: '224 (2 třídy)',
      rangeKm: 7300,
      cruiseSpeedKmh: 851,
      cruiseMach: 0.80,
      wingspanM: 47.57,
      lengthM: 48.51,
      heightM: 15.85,
      fuselageWidthM: 5.03,
      wingAreaM2: 283.3,
      mtowTonnes: 142.8,
      engineCount: 2,
      engineType: 'Pratt & Whitney JT9D-7R4 / PW4000 / GE CF6',
      firstFlightYear: 1981,
    }
  },
  {
    id: 'boeing-767-300',
    name: 'Boeing 767-300',
    modelSeries: '767 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Prodloužená verze o zhruba 6,4 metru, představená v roce 1986. Především ve verzi s prodlouženým doletem (300ER) se stala nekompromisně nejúspěšnějším modelem celé řady 767, oblíbeným pro lety přes Atlantik.',
    uniqueness: 'Díky skvělé ekonomice provozu a doletu prováděl v 90. letech více transatlantických letů než jakýkoli jiný letoun v historii.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Boeing_767-332-ER%2C_Delta_Air_Lines_JP7341811.jpg',
    authorName: 'Ryan Hothersall / Wikimedia Commons',
    specs: {
      capacityMax: 351,
      capacityTypical: '269 (3 třídy)',
      rangeKm: 11070,
      cruiseSpeedKmh: 851,
      cruiseMach: 0.80,
      wingspanM: 47.57,
      lengthM: 54.94,
      heightM: 15.85,
      fuselageWidthM: 5.03,
      wingAreaM2: 283.3,
      mtowTonnes: 186.8,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2 / Pratt & Whitney PW4000',
      firstFlightYear: 1986,
    }
  },
  {
    id: 'boeing-767-400er',
    name: 'Boeing 767-400ER',
    modelSeries: '767 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nejdelší a nejmodernější verze rodiny 767, prodloužená o dalších 6,4 metru oproti verzi -300. Byla navržena koncem 90. let jako náhrada starších letounů L-1011 a DC-10 pro společnosti Delta a United.',
    uniqueness: 'Disponuje zvětšeným rozpětím křídel s moderními zkosenými konci křídel (raked wingtips) a modernizovaným interiérem ve stylu Boeingu 777.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Delta_Air_Lines_Boeing_767-400ER_N835MH_at_LAX.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 375,
      capacityTypical: '304 (2 třídy)',
      rangeKm: 10415,
      cruiseSpeedKmh: 851,
      cruiseMach: 0.80,
      wingspanM: 51.92,
      lengthM: 61.37,
      heightM: 16.8,
      fuselageWidthM: 5.03,
      wingAreaM2: 290.7,
      mtowTonnes: 204.1,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2B / Pratt & Whitney PW4062',
      firstFlightYear: 2000,
    }
  },
  {
    id: 'boeing-767-300f',
    name: 'Boeing 767-300F',
    modelSeries: '767 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Přímo z výroby postavená čistě nákladní verze (Freighter) velmi úspěšného modelu -300. Slouží k přepravě velkoobjemových nákladů na středních a dlouhých tratích a těší se obrovské oblibě u FedEx, UPS či DHL.',
    uniqueness: 'Nemá kabinová okna ani klasické dveře pro cestující, je však vybaven mimořádně rozměrnými nákladovými dveřmi na hlavní palubě a automatizovaným nakládacím systémem.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/FedEx_Express_Boeing_767-300F_N101FE_at_LAX.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (Až 24 palet)',
      rangeKm: 6025,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 47.57,
      lengthM: 54.94,
      heightM: 15.85,
      fuselageWidthM: 5.03,
      wingAreaM2: 283.3,
      mtowTonnes: 186.8,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2 / Pratt & Whitney PW4062',
      firstFlightYear: 1995,
    }
  },
  {
    id: 'boeing-767-300bcf',
    name: 'Boeing 767-300BCF',
    modelSeries: '767 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Přestavěná nákladní verze (Boeing Converted Freighter) vzniklá modifikací původně osobních letadel 767-300. Představuje cenově efektivní způsob, jak uvést vyřazená osobní letadla zpět do vysoce produktivní služby.',
    uniqueness: 'Umožňuje prodloužit životnost draků letadel o desítky let a dává menším cargo dopravcům přístup k vysoce spolehlivé širokotrupé kapacitě.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/All_Nippon_Airways_Cargo_Boeing_767-300BCF_JA8356.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (Až 24 palet)',
      rangeKm: 6025,
      cruiseSpeedKmh: 850,
      cruiseMach: 0.80,
      wingspanM: 47.57,
      lengthM: 54.94,
      heightM: 15.85,
      fuselageWidthM: 5.03,
      wingAreaM2: 283.3,
      mtowTonnes: 186.8,
      engineCount: 2,
      engineType: 'General Electric CF6-80C2 / Pratt & Whitney PW4000',
      firstFlightYear: 2007,
    }
  },
  {
    id: 'boeing-777-200',
    name: 'Boeing 777-200',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Původní a nejkratší varianta řady 777, která poprvé vzlétla v roce 1994 a do služby vstoupila v roce 1995. Byla navržena primárně pro vnitrostátní a dálkové tratě s menší hustotou cestujících.',
    uniqueness: 'Jedná se o první komerční letadlo na světě, které bylo kompletně navrženo na počítačích pomocí 3D CAD systému CATIA, zcela bez nutnosti výroby fyzických maket.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/United_Airlines_Boeing_777-222_N774UA_at_LHR.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '305 (3 třídy)',
      rangeKm: 9700,
      cruiseSpeedKmh: 892,
      cruiseMach: 0.84,
      wingspanM: 60.9,
      lengthM: 63.7,
      heightM: 18.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 427.8,
      mtowTonnes: 247.2,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW4000 / Rolls-Royce Trent 800 / General Electric GE90',
      firstFlightYear: 1994,
    }
  },
  {
    id: 'boeing-777-200er',
    name: 'Boeing 777-200ER',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Verze s prodlouženým doletem (Extended Range), která se stala jedním z komerčně nejužitečnějších dálkových letadel. Zvýšená kapacita palivových nádrží a vyšší maximální vzletová hmotnost jí umožnily snadno létat přes oceány.',
    uniqueness: 'V roce 1997 vytvořil letoun této verze společnosti Malaysia Airlines rekord v délce letu bez mezipřistání, když uletěl 20 044 km ze Seattlu do Kuala Lumpur za 21 hodin a 23 minut.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/British_Airways_Boeing_777-200_G-YMMB.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '313 (3 třídy)',
      rangeKm: 13080,
      cruiseSpeedKmh: 892,
      cruiseMach: 0.84,
      wingspanM: 60.93,
      lengthM: 63.73,
      heightM: 18.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 427.8,
      mtowTonnes: 297.5,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW4090 / Rolls-Royce Trent 895 / General Electric GE90-94B',
      firstFlightYear: 1996,
    }
  },
  {
    id: 'boeing-777-300',
    name: 'Boeing 777-300',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Prodloužená verze modelové řady -200 o úctyhodných 10,13 metru. Byla navržena primárně jako náhrada starších verzí legendárního Boeingu 747 s podobnou kapacitou, ale se zlomkem spotřeby paliva.',
    uniqueness: 'V době svého představení v roce 1997 to byl nejdelší civilní dopravní letoun na světě, překonávající o více než 3 metry i tehdejší Boeing 747-400.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Cathay_Pacific_Boeing_777-300_B-HNE_at_NRT.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 550,
      capacityTypical: '368 (3 třídy)',
      rangeKm: 11135,
      cruiseSpeedKmh: 892,
      cruiseMach: 0.84,
      wingspanM: 60.93,
      lengthM: 73.86,
      heightM: 18.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 427.8,
      mtowTonnes: 299.3,
      engineCount: 2,
      engineType: 'Pratt & Whitney PW4098 / Rolls-Royce Trent 892 / General Electric GE90-94B',
      firstFlightYear: 1997,
    }
  },
  {
    id: 'boeing-777-300er',
    name: 'Boeing 777-300ER',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nejúspěšnější, nejprodávanější a nejznámější verze rodiny 777. Spojuje obrovskou kapacitu s doletem přes 13 600 km a stala se páteří dálkových flotil drtivé většiny prestižních aerolinek po celém světě.',
    uniqueness: 'Je vybavena legendárními obřími motory General Electric GE90-115B, které byly dlouho zapsány v Guinnessově knize rekordů jako nejvýkonnější proudové motory v historii letectví.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/10/Boeing_777-300ER%2C_Emirates_JP7946114.jpg',
    authorName: 'Ryan Hothersall / Wikimedia Commons',
    specs: {
      capacityMax: 550,
      capacityTypical: '396 (3 třídy)',
      rangeKm: 13650,
      cruiseSpeedKmh: 892,
      cruiseMach: 0.84,
      wingspanM: 64.8,
      lengthM: 73.9,
      heightM: 18.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 436.8,
      mtowTonnes: 351.5,
      engineCount: 2,
      engineType: 'General Electric GE90-115B',
      firstFlightYear: 2003,
    }
  },
  {
    id: 'boeing-777-200lr',
    name: 'Boeing 777-200LR',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Verze s extrémním doletem (Longer Range), přezdívaná „Worldliner“. Byla navržena tak, aby dokázala bez přestávky spojit prakticky jakákoli dvě významná města na zeměkouli.',
    uniqueness: 'Je držitelem absolutního světového rekordu v délce non-stop letu komerčního letadla (21 602 km z Hongkongu do Londýna východním směrem přes Pacifik a Atlantik) trvajícího 22 hodin a 42 minut.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Air_Canada_Boeing_777-233LR_C-FIUF_at_YVR.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '301 (3 třídy)',
      rangeKm: 15840,
      cruiseSpeedKmh: 892,
      cruiseMach: 0.84,
      wingspanM: 64.8,
      lengthM: 63.73,
      heightM: 18.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 436.8,
      mtowTonnes: 347.5,
      engineCount: 2,
      engineType: 'General Electric GE90-110B1 / GE90-115B',
      firstFlightYear: 2005,
    }
  },
  {
    id: 'boeing-777f',
    name: 'Boeing 777F',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Celosvětově mimořádně populární specializovaná nákladní verze (Freighter) postavená na konstrukčním základě modelů -200LR a -300ER. Nabízí skvělou efektivitu pro dálkovou přepravu těžkých nákladů.',
    uniqueness: 'Umožňuje naložit až 102 metrických tun nákladu a s plným naložením uletět non-stop přes 9 000 km, což z něj činí nejoblíbenější širokotrupé cargo současnosti.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/FedEx_Express_Boeing_777-FHT_N852FD_at_LAX.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 0,
      capacityTypical: 'Nákladní (Až 27 palet)',
      rangeKm: 9200,
      cruiseSpeedKmh: 892,
      cruiseMach: 0.84,
      wingspanM: 64.8,
      lengthM: 63.73,
      heightM: 18.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 436.8,
      mtowTonnes: 347.8,
      engineCount: 2,
      engineType: 'General Electric GE90-110B1L / GE90-115B',
      firstFlightYear: 2008,
    }
  },
  {
    id: 'boeing-777-8',
    name: 'Boeing 777-8',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Cestovní letoun nové generace s kódovým označením 777X. Je určen pro dálkové ultradlouhé trasy a představuje přímého technologického konkurenta moderního evropského Airbusu A350-1000.',
    uniqueness: 'Má obří kompozitní křídlo vyvinuté pomocí nejmodernějších technologií s unikátním mechanismem sklopných konců, které se po přistání složí nahoru, aby mohl letoun parkovat u standardních letištních stojánek.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Boeing_777-9_N779X_at_Paris_Air_Show_2023.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 395,
      capacityTypical: '384 (2 třídy)',
      rangeKm: 16170,
      cruiseSpeedKmh: 900,
      cruiseMach: 0.85,
      wingspanM: 71.75,
      lengthM: 69.79,
      heightM: 19.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 466.8,
      mtowTonnes: 351.5,
      engineCount: 2,
      engineType: 'General Electric GE9X-105B1A',
      firstFlightYear: 2026,
    }
  },
  {
    id: 'boeing-777-9',
    name: 'Boeing 777-9',
    modelSeries: '777 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Největší dvoumotorový dálkový letoun v historii lidstva z nejnovější řady 777X. Nabízí nevídanou úsporu paliva, tišší kabinu se zvětšenými okny a vyšší vlhkostí vzduchu pro snížení únavy při dlouhých letech.',
    uniqueness: 'Se sedmasedmdesáti metry délky se jedná o vůbec nejdelší aktivní dopravní letadlo na světě, poháněné gigantickými motory GE9X, které jsou široké jako celý trup běžného Boeingu 737.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Boeing_777X_777-9_N779XX_BFI.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 426,
      capacityTypical: '426 (2 třídy)',
      rangeKm: 13500,
      cruiseSpeedKmh: 900,
      cruiseMach: 0.85,
      wingspanM: 71.75,
      lengthM: 76.72,
      heightM: 19.5,
      fuselageWidthM: 6.2,
      wingAreaM2: 466.8,
      mtowTonnes: 351.5,
      engineCount: 2,
      engineType: 'General Electric GE9X-105B1A',
      firstFlightYear: 2020,
    }
  },
  {
    id: 'boeing-787-8',
    name: 'Boeing 787-8',
    modelSeries: '787 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Základní a nejkratší verze rodiny Dreamliner, zavedená do služby v roce 2011. Byla navržena s cílem nahradit starší stroje Boeing 767 a nabídnout mimořádnou efektivitu na dálkových linkách s nižším počtem cestujících.',
    uniqueness: 'Je to vůbec první dálkové letadlo na světě, jehož drak a nosná kostra jsou tvořeny z více než 50 % z pokročilých polymerních uhlíkových kompozitů. Pevnost kompozitů zaručuje, že se křídla za letu ohýbají nahoru s průhybem až 3 metry.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Boeing_787-8_Dreamliner%2C_All_Nippon_Airways_JP7194605.jpg',
    authorName: 'Paul Spijkers / Wikimedia Commons',
    specs: {
      capacityMax: 359,
      capacityTypical: '242 (3 třídy)',
      rangeKm: 13530,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 60.17,
      lengthM: 56.7,
      heightM: 16.9,
      fuselageWidthM: 5.77,
      wingAreaM2: 325.0,
      mtowTonnes: 227.9,
      engineCount: 2,
      engineType: 'General Electric GEnx-1B / Rolls-Royce Trent 1000',
      firstFlightYear: 2009,
    }
  },
  {
    id: 'boeing-787-9',
    name: 'Boeing 787-9',
    modelSeries: '787 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Prodloužená verze Dreamlineru o více než 6 metrů, která se stala komerčně nejprodávanějším a nejpopulárnějším modelem celé řady. Nabízí skvělý poměr mezi doletem, kapacitou a provozními náklady.',
    uniqueness: 'Díky vylepšené aerodynamice a větší kapacitě paliva má ze všech tří modelů Dreamlineru vůbec nejdelší dolet, dosahující přes 14 000 kilometrů.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Air_France_Boeing_787-9_F-HRBA_at_CDG.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 420,
      capacityTypical: '290 (3 třídy)',
      rangeKm: 14140,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 60.17,
      lengthM: 62.8,
      heightM: 17.02,
      fuselageWidthM: 5.77,
      wingAreaM2: 325.0,
      mtowTonnes: 254.0,
      engineCount: 2,
      engineType: 'General Electric GEnx-1B / Rolls-Royce Trent 1000',
      firstFlightYear: 2013,
    }
  },
  {
    id: 'boeing-787-10',
    name: 'Boeing 787-10',
    modelSeries: '787 Family',
    manufacturer: 'Boeing',
    country: 'USA',
    category: 'Širokotrupá (Wide-Body)',
    description: 'Nejdelší verze rodiny 787, prodloužená o dalších 5,5 metru oproti verzi -9. Je navržena tak, aby konkurovala Airbusu A350-900 a nahradila starší letadla na linkách s velkou hustotou provozu, přičemž sdílí více než 95 % dílů s verzí -9.',
    uniqueness: 'Díky prodlouženému trupu pojme až o 15 % více cestujících než verze -9, a přesto vykazuje o 25 % nižší emise a spotřebu na sedadlo než letadla, která nahrazuje.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Singapore_Airlines_Boeing_787-10_9V-SCA_at_SIN.jpg',
    authorName: 'Wikimedia Commons',
    specs: {
      capacityMax: 440,
      capacityTypical: '330 (3 třídy)',
      rangeKm: 11910,
      cruiseSpeedKmh: 903,
      cruiseMach: 0.85,
      wingspanM: 60.17,
      lengthM: 68.3,
      heightM: 17.02,
      fuselageWidthM: 5.77,
      wingAreaM2: 325.0,
      mtowTonnes: 254.0,
      engineCount: 2,
      engineType: 'General Electric GEnx-1B / Rolls-Royce Trent 1000',
      firstFlightYear: 2017,
    }
  }
];
